### ISSUE TITLE
Incorrect error message for HABTM join on missing primary key

### ISSUE THREAD

**Issue by IvanTrendafilov** [cakephp/cakephp#10054]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: PHP 7.0.8-3ubuntu3, PostgreSQL 9.6.1

### What you did
Attempted to join two tables: Users (users) and Groups (groups), linked with a HABTM relation on a join table GroupsUsers (groups_users). Users table has a primary key id, GroupsUsers has a primary key id, Groups *did not* have a primary key.

Cake fails to perform the join (as expected), but outputs a wrong error message in the log:

`2017-01-17 15:49:07 Error: [RuntimeException] The "groups_users" table does not define a primary key. Please set one.`

This is incorrect, it should, instead, output that the "groups" table does not define a primary key.

This gets triggered using a standard ORM query: `$this->Users->find($id, ['contain' => 'Groups']);`

**Comment by markstory** [comment]
What is the stack trace on that error?

**Comment by IvanTrendafilov** [comment]
```
2017-01-17 15:49:21 Error: [RuntimeException] The "groups_users" table does not define a primary key. Please set one.
Request URL: REDACTED
Client IP: REDACTED
Stack Trace:
#0 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Association.php(558): Cake\ORM\Association->_joinCondition(Array)
#1 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Association/BelongsToMany.php(1227): Cake\ORM\Association->attachTo(Object(Cake\ORM\Query))
#2 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Association/SelectableAssociationTrait.php(47): Cake\ORM\Association\BelongsToMany->_buildQuery(Array)
#3 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/EagerLoader.php(584): Cake\ORM\Association\BelongsToMany->eagerLoader(Array)
#4 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Query.php(938): Cake\ORM\EagerLoader->loadExternal(Object(Cake\ORM\Query), Object(Cake\Database\Statement\BufferedStatement))
#5 /ebs/torch/torch/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(272): Cake\ORM\Query->_execute()
#6 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Query.php(888): Cake\ORM\Query->_all()
#7 /ebs/torch/torch/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(395): Cake\ORM\Query->all()
#8 /ebs/torch/torch/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(406): Cake\ORM\Query->first()
#9 /ebs/torch/torch/vendor/cakephp/cakephp/src/ORM/Table.php(1202): Cake\ORM\Query->firstOrFail()
#10 /ebs/torch/torch/src/Controller/AppController.php(420): Cake\ORM\Table->get(Array, Array)
#11 /ebs/torch/torch/src/Controller/OrganizationsController.php(18): App\Controller\AppController->initialize()
#12 /ebs/torch/torch/vendor/cakephp/cakephp/src/Controller/Controller.php(262): App\Controller\OrganizationsController->initialize()
#13 [internal function]: Cake\Controller\Controller->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Organizations')
#14 /ebs/torch/torch/vendor/cakephp/cakephp/src/Routing/Filter/ControllerFactoryFilter.php(100): ReflectionClass->newInstance(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Organizations')
#15 /ebs/torch/torch/vendor/cakephp/cakephp/src/Routing/Filter/ControllerFactoryFilter.php(51): Cake\Routing\Filter\ControllerFactoryFilter->_getController(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 /ebs/torch/torch/vendor/cakephp/cakephp/src/Routing/DispatcherFilter.php(145): Cake\Routing\Filter\ControllerFactoryFilter->beforeDispatch(Object(Cake\Event\Event))
#17 /ebs/torch/torch/vendor/cakephp/cakephp/src/Event/EventManager.php(411): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#18 /ebs/torch/torch/vendor/cakephp/cakephp/src/Event/EventManager.php(373): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#19 /ebs/torch/torch/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#20 /ebs/torch/torch/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#21 /ebs/torch/torch/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#22 {main}
```

**Comment by markstory** [comment]
Thanks! I'll look into reproducing and getting the error message fixed up.

**Comment by markstory** [comment]
Pull request up now.
