### ISSUE TITLE
Bake Models failed when file already exists under certains cicomstance

### ISSUE THREAD

**Issue by jonathanlaf** [cakephp/cakephp#10191]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.13
* Platform and Target: Wamp for my PHP, MySQL on a CENTOS (cPanel) for MySQL, baked through PhpStorm 2016.3.2 Terminal.

Here is a list of command that make it happen

`cake bake all product_options`
Here everythings was fine, but I had to modify some FK and change some fieldnames, I've manually updated my controller and CTP since there where already customisation made on thoses files, but I wanted to make sure models and entity was well set so I ran
`cake bake model productoptions`
It's not a typo in my description, it was a typo on my command line, I forgot the "_" but cake was intelligent enough to make it's way and rebuild my models, but he build it without any camelCase, so I ran it again
`cake bake model product_options`
And bam, I got :
```
One moment while associations are detected.
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'clientDB.productoptions' doesn't exist in [F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Database\Schema\Collection.php, line 131]
2017-02-09 21:49:22 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'clientDB.productoptions' doesn't exist
Stack Trace:
#0 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(97): Cake\Database\Schema\Collection->_reflect('Column', 'productoptions', Array, Object(Cake\Database\Schema\Table))
#1 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(63): Cake\Database\Schema\Collection->describe('productoptions', Array)
#2 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\ORM\Table.php(440): Cake\Database\Schema\CachedCollection->describe('productoptions')
#3 F:\Sites\ClientName\public_html\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(266): Cake\ORM\Table->schema()
#4 F:\Sites\ClientName\public_html\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(216): Bake\Shell\Task\ModelTask->findBelongsTo(Object(App\Model\Table\ProductoptionsTable), Array)
#5 F:\Sites\ClientName\public_html\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(127): Bake\Shell\Task\ModelTask->getAssociations(Object(App\Model\Table\ProductoptionsTable))
#6 F:\Sites\ClientName\public_html\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(110): Bake\Shell\Task\ModelTask->getTableContext(Object(App\Model\Table\ProductoptionsTable), 'product_options', 'ProductOptions')
#7 F:\Sites\ClientName\public_html\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(97): Bake\Shell\Task\ModelTask->bake('ProductOptions')
#8 [internal function]: Bake\Shell\Task\ModelTask->main('product_options')
#9 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Console\Shell.php(472): call_user_func_array(Array, Array)
#10 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Console\Shell.php(465): Cake\Console\Shell->runCommand(Array, false, Array)
#11 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(227): Cake\Console\Shell->runCommand(Array, true, Array)
#12 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#13 F:\Sites\ClientName\public_html\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#14 F:\Sites\ClientName\public_html\bin\cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#15 {main}
```

**Comment by markstory** [comment]
What are you expecting to happen when you make a mistake like that?

**Comment by ravage84** [comment]
Personally, I do not expect it, but the console _could_ ask me something like:

"Table not found. Did you mean xxx instead of yyy?"

But that would mean the Bake logic would do some guessing for you.
Not sure if that's worth it.

**Comment by dereuromark** [comment]
I would also not complicate things here. I think the current behavior is fine.
But if someone wanted to provide a PR to improve the error message, that sounds also good.

**Comment by markstory** [comment]
This issue was moved to cakephp/bake#311

**Comment by jonathanlaf** [comment]
Sorry I was on vacation, what I was expecting, since it worked with underscore and without underscore, I was wondering why it was not respecting the naming convention ?
