### ISSUE TITLE
Fixture records generation with bake and custom data types throw exception when tests are run

### ISSUE THREAD

**Issue by calcosta** [cakephp/cakephp#10396]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2. Bake: 1.3.1
* Platform and Target: Ubuntu 16.04, Apache 2.4.18, MySQL 5.7..17, PHP 7.0.15-0ubuntu0.16.04.4, PHPUnit 6.0.8

### What you did
I used fixture generation with records `bin/cake bake fixture all -n 1000 -f -r`.
My app is using custom Data Type as described in the docs here: [https://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-types](https://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-types)
exactly like the example (json type).

### What happened
Fixture generation generates fixture code like e.g.:
```
public $records = [
        [
            'id' => 15,
            'images' => array (
                  0 => 
                  array (
                    'file' => 'picture.jpg',
                    'caption' => 'Flower'
                  )
            ),
[...]
```
When fixtures are saved to the test DB during testing the following exception is thrown:
```
2017-03-10 13:01:58 Error: [InvalidArgumentException] Cannot convert value to string
Stack Trace:
#0 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/TypeConverterTrait.php(37): Cake\Database\Type\StringType->toDatabase(Array, Object(Cake\Database\Driver\Mysql))
#1 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/Statement/PDOStatement.php(73): Cake\Database\Statement\StatementDecorator->cast(Array, Object(Cake\Database\Type\StringType))
#2 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/ValueBinder.php(147): Cake\Database\Statement\PDOStatement->bindValue('c5', Array, 'text')
#3 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/Connection.php(303): Cake\Database\ValueBinder->attachTo(Object(Cake\Database\Statement\MysqlStatement))
#4 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/Query.php(213): Cake\Database\Connection->run(Object(Cake\Database\Query))
#5 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php(353): Cake\Database\Query->execute()
#6 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php(329): Cake\TestSuite\Fixture\TestFixture->insert(Object(Cake\Database\Connection))
#7 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php(370): Cake\TestSuite\Fixture\FixtureManager->Cake\TestSuite\Fixture\{closure}(Object(Cake\Database\Connection), Array)
#8 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/Connection.php(687): Cake\TestSuite\Fixture\FixtureManager->Cake\TestSuite\Fixture\{closure}(Object(Cake\Database\Connection))
#9 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php(371): Cake\Database\Connection->disableConstraints(Object(Closure))
#10 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/Database/Connection.php(654): Cake\TestSuite\Fixture\FixtureManager->Cake\TestSuite\Fixture\{closure}(Object(Cake\Database\Connection))
#11 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php(372): Cake\Database\Connection->transactional(Object(Closure))
#12 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php(341): Cake\TestSuite\Fixture\FixtureManager->_runOperation(Array, Object(Closure))
#13 /mnt/websites/volleybaer_cake3/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php(174): Cake\TestSuite\Fixture\FixtureManager->load(Object(App\Test\TestCase\Controller\Component\CartComponentTest))
#14 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/Framework/TestResult.php(396): Cake\TestSuite\Fixture\FixtureInjector->startTest(Object(App\Test\TestCase\Controller\Component\CartComponentTest))
#15 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/Framework/TestResult.php(630): PHPUnit\Framework\TestResult->startTest(Object(App\Test\TestCase\Controller\Component\CartComponentTest))
#16 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/Framework/TestCase.php(867): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\Component\CartComponentTest))
#17 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/Framework/TestSuite.php(739): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#18 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/Framework/TestSuite.php(739): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#19 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(514): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#20 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/TextUI/Command.php(207): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#21 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/src/TextUI/Command.php(136): PHPUnit\TextUI\Command->run(Array, true)
#22 /mnt/websites/volleybaer_cake3/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#23 {main}
```

### What you expected to happen
Fixtures should be inserted correctly after been generated with bake.

Either fixture generation should deal (skip?!) with custom data type callbacks or when fixture data is saved, the responsible custom data type callbacks should be called.

**Comment by markstory** [comment]
What is the custom data type you are using for the `images` column?

**Comment by calcosta** [comment]
I use the `json` data type for the images column.

This is the Database/Type/JsonType.php:
```
<?php
namespace App\Database\Type;

use Cake\Database\Driver;
use Cake\Database\Type;
use PDO;

class JsonType extends Type
{

    public function toPHP($value, Driver $driver)
    {
        if ($value === null) {
            return null;
        }
        return json_decode($value, true);
    }

    public function marshal($value)
    {
        if (is_array($value) || $value === null) {
            return $value;
        }
        return json_decode($value, true);
    }

    public function toDatabase($value, Driver $driver)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }

    public function toStatement($value, Driver $driver)
    {
        if ($value === null) {
            return PDO::PARAM_NULL;
        }
        return PDO::PARAM_STR;
    }

}
```

and this is the ArticlesTable:
```
protected function _initializeSchema(\Cake\Database\Schema\TableSchema $schema)
    {
        $schema->columnType('sizes', 'json');
        $schema->columnType('images', 'json');
        return $schema;
    }
```

**Comment by markstory** [comment]
Thanks. What does your schema for that table look like? Is the fixture importing schema?

**Comment by calcosta** [comment]
The Fixture does not import schema. The fields are defined like this:
```
class ArticlesFixture extends TestFixture
{

    /**
     * Fields
     *
     * @var array
     */
    // @codingStandardsIgnoreStart
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 11, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
        'company_id' => ['type' => 'integer', 'length' => 11, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'autoIncrement' => null],
        'name' => ['type' => 'string', 'length' => 255, 'null' => false, 'default' => null, 'collate' => 'utf8_unicode_ci', 'comment' => '', 'precision' => null, 'fixed' => null],
        'slug' => ['type' => 'text', 'length' => null, 'null' => false, 'default' => null, 'collate' => 'utf8_unicode_ci', 'comment' => '', 'precision' => null],
        'images' => ['type' => 'text', 'length' => null, 'null' => false, 'default' => null, 'collate' => 'utf8_unicode_ci', 'comment' => '', 'precision' => null],
[...]

public $records = [
        [
            'id' => 15,
[...]
```

The Schema of the table is:
```
CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` text COLLATE utf8_unicode_ci NOT NULL,
  `images` text COLLATE utf8_unicode_ci NOT NULL,
[...]
```

**Comment by markstory** [comment]
Ok. I will try to reproduce with that information.

**Comment by markstory** [comment]
You need to update your fixtures to use `'type' => 'json'` instead of `'type' => 'text'` for the columns that have been re-mapped. Bake does not use the augmented schema defined in the table class, and instead relies entirely on direct schema reflection.

**Comment by calcosta** [comment]
Ok, thanks a lot!
