### ISSUE TITLE
[3.5.1 Cookie] [InvalidArgumentException] The provided arg must be of type `bool` but `integer` given

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#11120]
Error:
```
2017-08-30 13:03:52 Error: [InvalidArgumentException] The provided arg must be of type `bool` but `integer` given
Request URL: /shopify/webhook/update-product
Stack Trace:
#0 /www/slshop/vendor/cakephp/cakephp/src/Http/Cookie/Cookie.php(147): Cake\Http\Cookie\Cookie->validateBool(0)
#1 /www/slshop/vendor/cakephp/cakephp/src/Http/Response.php(1975): Cake\Http\Cookie\Cookie->__construct('locale', 'en_US', Object(DateTime), '/', '.sellazy.com', 0, false)
```

CookieComponent:

```php
        $this->loadComponent('Cookie', [
            'encryption' => false,
            'path' => '/',
            'domain' => env('COOKIE_DOMAIN'),
            'secure' => 0
        ]);
```

I have set "false" for argument "secure" to solve this. However 3.5 is not backward compatible.  which makes me dare not upgrade to 3.5 from 3.4.

**Comment by markstory** [comment]
The `secure` was always supposed to be a boolean though. You were leveraging type juggling before. We could add typecasting into `CookieComponent` to make it more backwards compatible though.

**Comment by markstory** [comment]
Pull request open now.
