### ISSUE TITLE
Integration Test AJAX Controller Action PUT method (follow-up from #11325)

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#11401]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.5
### What you did
see Issue #11325, additionally SecurityComponent is enabled in AppController forcing ssl as described in cakephp docs.

In ControllerTestCase

```php
        $this->enableCsrfToken();
        $this->enableSecurityToken();
        $this->configRequest([
            'headers' => [
                'Accept' => 'application/json',
                'X-Requested-With' => 'XMLHttpRequest',
            ]
        ]);

        $data = [
            'id' => 1,
            'total_price' => '0,0244',
        ];

        $result = $this->put('/prices/x-editable-endpoint.json', json_encode($data));
```

### What happened
response is empty, cli-error.log shows
```log
#14 .\src\Controller\AppController.php(96): Cake\Controller\Controller->redirect('https:///my...')
#15 [internal function]: App\Controller\AppController->forceSSL('auth', Object(Cake\Controller\Exception\AuthSecurityException))
#16 .\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(597): call_user_func_array(Array, Array)
#17 .\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(190): Cake\Controller\Component\SecurityComponent->_callback(Object(App\Controller\MyController), 'forceSSL', Array)
#18 .\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(124): Cake\Controller\Component\SecurityComponent->blackHole(Object(App\Controller\MyController), 'auth', Object(Cake\Controller\Exception\AuthSecurityException))
#19 .\vendor\cakephp\cakephp\src\Event\EventManager.php(416): Cake\Controller\Component\SecurityComponent->startup(Object(Cake\Event\Event))
```

### What you expected to happen
controller action should be executed. works in real life scenarios without problems.

**Comment by markstory** [comment]
If you're stringifying the data, how is the token supposed to be inserted into the POST data?

**Comment by swiffer** [comment]
To be honest I don't know. But why is it working in browsers then? I used the cakephp/app skeleton for my project. I'll add some more code below.

AppController.php
```php
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        /*
         * Enable form based authentification component.
         * see https://book.cakephp.org/3.0/en/controllers/components/authentication.html
         */
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password'
                    ]
                ]
            ],
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login'
            ],
            'loginRedirect' => [
                'controller' => 'Users',
                'action' => 'dashboard'
            ],
            'authorize' => 'Controller',
        ]);

        /*
         * Enable the following components for recommended CakePHP security settings.
         * see https://book.cakephp.org/3.0/en/controllers/components/security.html
         */
        $this->loadComponent('Security', ['blackHoleCallback' => 'forceSSL']);
    }

    /**
     * beforeFilter callback.
     *
     * @param \Cake\Event\Event $event Event.
     * @return \Cake\Http\Response|null|void
     */
    public function beforeFilter(Event $event)
    {
        $this->Security->requireSecure();
    }

    /**
     * Callback for redirecting users to https version of current request.
     *
     * @return \Cake\Http\Response|null|void
     */
    public function forceSSL()
    {
        return $this->redirect('https://' . env('SERVER_NAME') . $this->request->here());
    }
```

PricesController.php
```php
    /**
     * XEditableEndpoint method
     *
     * @return \Cake\Http\Response|void
     */
    public function xEditableEndpoint()
    {
        if ($this->request->is(['ajax'])) {
            $data = $this->request->input('json_decode', true);
            $id = $data['id'];

            ...

        }
    }
```

PricesControllerTest.php
```php
    /**
     * Test x-editable-endpoint method
     *
     * @return void
     */
    public function testXEditableEndpoint()
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        $this->configRequest([
            'headers' => [
                'Accept' => 'application/json',
                'X-Requested-With' => 'XMLHttpRequest',
            ]
        ]);

        $this->session([
            'Auth' => [
                'User' => [
                    'id' => 1,
                    'name' => 'Stefan M Ritter',
                    'role' => 'admin',
                    'company_id' => null,
                ]
            ]
        ]);

        $data = [
            'id' => 1,
            'total_price' => '0,0244',
        ];

        $result = $this->put('/prices/x-editable-endpoint.json', json_encode($data));
        $price = $this->Prices->get(1);

        $this->assertEquals(0.0244, $price->total_price);
        $this->assertResponseContains($result, '0,0244');
    }
```

cli-error.log
```log
2017-11-02 18:11:24 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/https:///prices/x-editable-endpoint.json" could not be found.
Exception Attributes: array (
  'url' => '/https:///prices/x-editable-endpoint.json',
)
Request URL: /prices/x-editable-endpoint.json
Stack Trace:
#0 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\Router.php(370): Cake\Routing\RouteCollection->parseRequest(Object(Cake\Http\ServerRequest))
#1 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\Filter\RoutingFilter.php(58): Cake\Routing\Router::parseRequest(Object(Cake\Http\ServerRequest))
#2 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(146): Cake\Routing\Filter\RoutingFilter->beforeDispatch(Object(Cake\Event\Event))
#3 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(416): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#5 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#6 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(78): Cake\Http\ActionDispatcher->dispatchEvent('Dispatcher.befo...', Array)
#7 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(60): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\RequestActionTrait.php(177): Cake\Routing\Dispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Component\RequestHandlerComponent.php(285): Cake\Controller\Controller->requestAction('https:///prices...', Array)
#10 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(416): Cake\Controller\Component\RequestHandlerComponent->beforeRedirect(Object(Cake\Event\Event), 'https:///prices...', Object(Cake\Http\Response))
#11 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#12 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#13 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Controller.php(551): Cake\Controller\Controller->dispatchEvent('Controller.befo...', Array)
#14 C:\Websites\edilyze\src\Controller\AppController.php(96): Cake\Controller\Controller->redirect('https:///prices...')
#15 [internal function]: App\Controller\AppController->forceSSL('auth', Object(Cake\Controller\Exception\AuthSecurityException))
#16 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(597): call_user_func_array(Array, Array)
#17 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(190): Cake\Controller\Component\SecurityComponent->_callback(Object(App\Controller\PricesController), 'forceSSL', Array)
#18 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(124): Cake\Controller\Component\SecurityComponent->blackHole(Object(App\Controller\PricesController), 'auth', Object(Cake\Controller\Exception\AuthSecurityException))
#19 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(416): Cake\Controller\Component\SecurityComponent->startup(Object(Cake\Event\Event))
#20 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#21 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#22 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Controller\Controller.php(506): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#23 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(114): Cake\Controller\Controller->startupProcess()
#24 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PricesController))
#25 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#26 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#27 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#29 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#30 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#31 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(95): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#33 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#34 C:\Websites\edilyze\vendor\cakephp\cakephp\src\Http\Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#35 C:\Websites\edilyze\vendor\cakephp\cakephp\src\TestSuite\MiddlewareDispatcher.php(97): Cake\Http\Server->run(Object(Cake\Http\ServerRequest))
#36 C:\Websites\edilyze\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php(484): Cake\TestSuite\MiddlewareDispatcher->execute(Array)
#37 C:\Websites\edilyze\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php(420): Cake\TestSuite\IntegrationTestCase->_sendRequest('/prices/x-edita...', 'PUT', '{"id":1,"total_...')
#38 C:\Websites\edilyze\tests\TestCase\Controller\PricesControllerTest.php(116): Cake\TestSuite\IntegrationTestCase->put('/prices/x-edita...', '{"id":1,"total_...')
#39 [internal function]: App\Test\TestCase\Controller\PricesControllerTest->testXEditableEndpoint()
#40 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(App\Test\TestCase\Controller\PricesControllerTest), Array)
#41 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestCase.php(939): PHPUnit\Framework\TestCase->runTest()
#42 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#43 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\PricesControllerTest))
#44 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestSuite.php(743): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#45 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/Framework/TestSuite.php(743): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#46 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#47 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#48 phar://C:/Tools/phpunit-6.4.3.phar/phpunit/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#49 C:\Tools\phpunit-6.4.3.phar(563): PHPUnit\TextUI\Command::main()
#50 {main}
```

**Comment by markstory** [comment]
> A route matching "/https:///prices/x-editable-endpoint.json"

This might be a relevant part. Looks like routing is failing before SecurityComponent is involved at all.

**Comment by swiffer** [comment]
Yes, I'm doing that in the init of IntegrationTest already. Works fine for different tests containing get requests in the same controller but the put request is failing.

```php
    public function setUp()
    {
        parent::setUp();

        // Fake out SSL connections.
        $this->configRequest([
            'environment' => ['HTTPS' => 'on']
        ]);
```

**Comment by markstory** [comment]
Ok. I have to assume that your JSON data contains the token inputs when the browser is sending the request then.  As it stands there isn't a way for the IntegrationTestCase to safely insert tokens into string data payloads as we don't have enough information on the structure and format of the data inside the strings.

You might want to consider providing your data as an array in your test case instead.

**Comment by swiffer** [comment]
ok, i added a check in controller action and use an array in testmethod now. works fine.

```php
            if (!is_null($this->request->getData('id'))) {
                $data = $this->request->getData();
            } else {
                $data = $this->request->input('json_decode', true);
            }
```

**Comment by markstory** [comment]
Sounds like you might want to explore the option of using RequestHandlerComponent as well. It will automatically decode json request bodies into arrays based on content type headers.

**Comment by swiffer** [comment]
Did that! Works fine, thanks i think this Issue can be closed.
