### ISSUE TITLE
Argument 1 passed to Cake\Error\ExceptionRenderer::__construct() must be an instance of Exception

### ISSUE THREAD

**Issue by psantos10** [cakephp/cakephp#11514]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.7
* Platform and Target: PHP 7.1.11; MariaDB 10.2.11

### What you did

I write this code on the controller:

```
$categories = TableRegistry::get('Categories');
$category = $categories->find('all');
```

### What happened

Gives me this error:

> Argument 1 passed to Cake\Error\ExceptionRenderer::__construct() must be an instance of Exception, instance of Error given, called in /home/psantos/Workspace/my_app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php on line 167

### What you expected to happen

I was expecting to get a more descriptive error info. no matter what change I do, I stil getting the same error.

**Comment by dereuromark** [comment]
We need to remove the typehint @ https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L88 for PHP7+.
Can you provide a patch PR maybe?

**Comment by chinpei215** [comment]
I don't think we can remove typehints in a bugfix release. I think this issue is caused by a recent patch for the ErrorHandlerMiddleware. We could revert it or enhance it to use PHP7ErrorException.

**Comment by dereuromark** [comment]
Typehints should be able to be removed if they fix these issues of PHP7 and broken code. But if you have an idea for enhancement, go for it.

**Comment by chinpei215** [comment]
It would be better to revert it, as I said in #11462. I am not sure what bug is solved this PR.
However, if it fixed  some bugs, then we mat need to fix this new bug without breaking BC. 
Note that I am not saying the PR is not good. It is really good. but we can do it in 3.6. then  we could change the problematic typehints too.

**Comment by dereuromark** [comment]
IMO the bigger issue is some php7 errors to not being logged, the typehint issue is minor in comparison.

**Comment by chinpei215** [comment]
As I said in the PR, I think PHP7 errors are logged correctly by the legacy ErrorHandler class even in 3.5.6 or earlier. But if you could show me some edge case that those are not logged, then I could understand what was a problem.

**Comment by dereuromark** [comment]
Custom error handler, see e.g. DatabaseLog plugin.

**Comment by chinpei215** [comment]
Do you have some code snippet that causes the problem?

**Comment by ADmad** [comment]
Perhaps this patch might fix the reported issue.

```php
diff --git a/src/Error/Middleware/ErrorHandlerMiddleware.php b/src/Error/Middleware/ErrorHandlerMiddleware.php
index 1529c3a..d848a0b 100644
--- a/src/Error/Middleware/ErrorHandlerMiddleware.php
+++ b/src/Error/Middleware/ErrorHandlerMiddleware.php
@@ -111,6 +111,10 @@ class ErrorHandlerMiddleware
      */
     public function handleException($exception, $request, $response)
     {
+        if ($exception instanceof \Error) {
+            $exception = new \Cake\Error\PHP7ErrorException($exception);
+        }
+
         $renderer = $this->getRenderer($exception);
         try {
             $res = $renderer->render();
```

**Comment by dereuromark** [comment]
Sure, we can try that.

**Comment by ADmad** [comment]
@psantos10 Can you try the patch I provided and report back?

**Comment by chinpei215** [comment]
Couldn't reproduce the DatabaseLog logging issues with CakePHP 3.4. But I would stop saying the same things again. Feel free to fix the new bug.
```
sqlite> SELECT * FROM database_logs;
1|error|[DivisionByZeroError] Modulo by zero in C:\var\www\cakephp.dev\app\webroot\3.x\src\Controller\TestsController.php on line 20
Request URL: /tests/
Client IP: 127.0.0.1
Stack Trace:
#0 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\TestsController->index()
#1 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#2 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\TestsController))
#3 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\var\www\cakephp.dev\app\webroot\3.4\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\var\www\cakephp.dev\app\webroot\3.4\webroot\index.php(40): Cake\Http\Server->run()
#16 {main}|Array
(
    [scope] => Array
        (
        )

)|2017-12-08 00:01:09|127.0.0.1|cakephp.dev|/3.4/tests/||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36|1
```

**Comment by psantos10** [comment]
@ADmad I think that now I am getting the proper error.

**Comment by dereuromark** [comment]
Please try https://github.com/cakephp/cakephp/pull/11518

**Comment by entheosweb** [comment]
@ADmad I was experiencing that issue too, and your fix solved it

**Comment by davidyell** [comment]
Just hit this today. I was surprised that a minor release broke my application! It's quite unlike CakePHP

**Comment by markstory** [comment]
@davidyell I'm planning on cutting another release tonight.
