### ISSUE TITLE
schema generate shell fails on enum column

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#12804]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.13.
* Platform and Target: Apache, MySQL.

### What you did
Run `./Console/cake schema generate`.

### What happened
The shell exited with errors:
```
val@val-desktop:~/git/app$ ./Console/cake schema generate

Welcome to CakePHP v2.10.13 Console
---------------------------------------------------------------
App : app
Path: /home/val/git/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Generating Schema...
Notice Error: Schema generation error: invalid column type enum('option 1','option 2','option 3') for MyModel.my_column does not exist in DBO in [/home/val/git/Cake/Model/CakeSchema.php, line 628]

Error: mymodel model not constructed properly
#0 [internal function]: AppMyModel->__construct(Array)
#1 /home/val/git/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#2 /home/val/git/Cake/Model/CakeSchema.php(248): ClassRegistry::init('AppMyMo...')
#3 /home/val/git/Cake/Console/Command/SchemaShell.php(148): CakeSchema->read(Array)
#4 /home/val/git/Cake/Console/Shell.php(459): SchemaShell->generate()
#5 /home/val/git/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('generate', Array)
#6 /home/val/git/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /home/val/git/Cake/Console/cake.php(54): ShellDispatcher::run(Array)
#8 {main}
```
(I changed some paths in the output above).

### What you expected to happen
According to the [cookbook](https://book.cakephp.org/2.0/en/console-and-shells/schema-management-and-migrations.html):
> This will generate a schema.php file in your app/Config/Schema directory

**Comment by markstory** [comment]
Enums are very poorly support in 2.x. Fixing this borders on a new feature.

**Comment by dereuromark** [comment]
PR open.
