### ISSUE TITLE
Inconsistent error output - UrlHelper / Router

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13040]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.3
* Platform and Target: linux nginx php7.3

Through custom `App\Error\AppExceptionRenderer` I'm disabling/enabling Debug status for rendering PHP handled errors using something like

```php
<?php

namespace App\Error;

use Cake\Core\Configure;
use Cake\Error\ExceptionRenderer;

class AppExceptionRenderer extends ExceptionRenderer
{

    public function render()
    {
        $is_debug = null;
        if ($this->controller && $this->controller->Auth && !empty($this->controller->Auth->user())) {
            // decide if the debug output should be shown, if that is so, set $is_debug to anything but null
        }



        if ($is_debug === null) {
            // not show dev_err layout for non-debug users
            Configure::write('debug', false);
        }

        return parent::render();
    }

}
```

In situation, where this code decides current user is not to be shown "dev_error layout, debug output", the error output is inconsistent

Two states are seen
  - Internal Server Error (500)
  - Not Found Exception (404)

**404 error** will show this stacktrace in `error.log` (accessing /en_US/wizarda, which is undefined route)

```log
2019-03-10 18:18:37 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/en_US/wizarda" could not be found.
#0 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Router.php(385): Cake\Routing\RouteCollection->parseRequest(Object(Cake\Http\ServerRequest))
#1 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(146): Cake\Routing\Router::parseRequest(Object(Cake\Http\ServerRequest))
#2 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Ca
ke\Http\Runner))
#3 /var/www/myapp/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object
(Cake\Http\Runner))
#5 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(108): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Objec
t(Cake\Http\Runner))
#7 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake
\Http\Runner))
#9 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /var/www/myapp/webroot/index.php(40): Cake\Http\Server->run()
#12 {main}
Request URL: /en_US/wizarda
```

**500 error** shows in `error.log` this way:
```log
2019-03-10 18:09:58 Error: [TypeError] Argument 2 passed to Cake\Http\BaseApplication::{closure}() must be an instance of Cake\Http\ServerRequest, null given, called in /var/www/myapp/vend
or/cakephp/cakephp/src/Routing/Router.php on line 589                                                                                                                                          
#0 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Router.php(589): Cake\Http\BaseApplication->{closure}(Array, NULL)                                                                     
#1 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Router.php(679): Cake\Routing\Router::_applyUrlFilters(Array)                                                                          
#2 /var/www/myapp/vendor/cakephp/cakephp/src/View/Helper/UrlHelper.php(56): Cake\Routing\Router::url(Array, false)                                                                          
#3 /var/www/myapp/src/Template/Layout/default.ctp(44): Cake\View\Helper\UrlHelper->build(Array)                                                                                             
#4 /var/www/myapp/vendor/cakephp/cakephp/src/View/View.php(1413): include('/var/www/certif...')                                                                                             
#5 /var/www/myapp/vendor/cakephp/cakephp/src/View/View.php(1374): Cake\View\View->_evaluate('/var/www/certif...', Array)                                                                    
#6 /var/www/myapp/vendor/cakephp/cakephp/src/View/View.php(927): Cake\View\View->_render('/var/www/certif...')                                                                              
#7 /var/www/myapp/vendor/cakephp/cakephp/src/View/View.php(885): Cake\View\View->renderLayout('', 'default')                                                                                
#8 /var/www/myapp/vendor/cakephp/cakephp/src/Controller/Controller.php(791): Cake\View\View->render('error400', NULL)                                                                       
#9 /var/www/myapp/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(369): Cake\Controller\Controller->render('error400')                                                               
#10 /var/www/myapp/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(244): Cake\Error\ExceptionRenderer->_outputMessage('error400')                                                    
#11 /var/www/myapp/src/Error/AppExceptionRenderer.php(29): Cake\Error\ExceptionRenderer->render()                                                                                           
#12 /var/www/myapp/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(118): App\Error\AppExceptionRenderer->render()                                                    
#13 /var/www/myapp/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(100): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(Cake\Routing\Exception\
MissingRouteException), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))                                                                                                           
#14 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Objec
t(Cake\Http\Runner))                                                                                                                                                                           
#15 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(108): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))    
#16 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Obje
ct(Cake\Http\Runner))                                                                                                                                                                          
#17 /var/www/myapp/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))           
#18 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cak
e\Http\Runner))                                                                                                                                                                                
#19 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))                                  
#20 /var/www/myapp/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))    
#21 /var/www/myapp/webroot/index.php(40): Cake\Http\Server->run()                                                                                                                           
#22 {main}                                                                                                                                                                                     
Request URL: /en_US/wizarda
```

The **500 error**, judging by stacktrace, originates from `Cake\Routing\Router.php:589` which is applying URL filtering (method signature `protected static function _applyUrlFilters($url){}`), and the request gathered on line `587` through `$request = static::getRequest(true)` returned is null

This causes UrlHelper to fail in non-`dev_err` layout (aka the `src/Template/Layout/default.ctp`) and the error shown is different.

However this seems to be the case in both errors, because HTML rendered looks like this:

**404**:
```html

<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8"/>    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
         myapp.eu
    </title>
    <link rel="icon" type="image/png" href="https://myapp.eu/favicon.png"/>
    <link rel="shortcut icon" href="https://myapp.eu/favicon.ico"/>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>    <link rel="stylesheet" href="/css/toggle-switch.css"/>    <link rel="stylesheet" href="/css/select2.min.css"/>    <link rel="stylesheet" href="/css/pikaday/pikaday.css"/>    <link rel="stylesheet" href="/css/myapp.css?rand=1793391118"/>    
    <script src="/js/jquery-3.3.1.min.js"></script>    <script src="/js/jquery.chained.selects.js?rand=1655205929"></script>    <script src="/js/select2.full.min.js"></script>    <script src="/js/moment-with-locales.js"></script>    <script src="/js/pikaday.js"></script>    <script src="/js/pikaday.jquery.js"></script>    <script src="/js/popper.min.js"></script>    <script src="/js/bootstrap.min.js"></script>    <script src="/js/d3.v5.js"></script>    <script src="/js/dagre-d3.js"></script>    <script src="/js/myapp.js?ramd=757005104"></script>
    </head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
    <a class="navbar-brand" href="/">
        <img src="/favicon.png" width="30" height="30" alt="myapp">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

                                        <li class="nav-item">
                    <a class="nav-link"
                       href="/user/dashboard">User dashboard</a>
                </li>
                <li class="nav-item">
                    <a href="<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>    <title>
        Error    </title>
    <link href="/favicon.ico" type="image/x-icon" rel="icon"/><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon"/>
    <link rel="stylesheet" href="/css/base.css"/>    <link rel="stylesheet" href="/css/style.css"/>
            </head>
<body>
<div id="container">
    <div id="header">
        <h1>Error</h1>
    </div>
    <div id="content">
        
        <h2>An Error Has Occurred</h2>
<p class="alert alert-danger">
    <strong>Error: </strong>
    Not Found</p>
    </div>
    <div id="footer">
        <a href="javascript:history.back()">Back</a>    </div>
</div>
</body>
</html>
```

and in **500**:
```html

<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8"/>    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
         myapp.eu
    </title>
    <link rel="icon" type="image/png" href="https://myapp.eu/favicon.png"/>
    <link rel="shortcut icon" href="https://myapp.eu/favicon.ico"/>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>    <link rel="stylesheet" href="/css/toggle-switch.css"/>    <link rel="stylesheet" href="/css/select2.min.css"/>    <link rel="stylesheet" href="/css/pikaday/pikaday.css"/>    <link rel="stylesheet" href="/css/myapp.css?rand=631317527"/>    
    <script src="/js/jquery-3.3.1.min.js"></script>    <script src="/js/jquery.chained.selects.js?rand=1712123251"></script>    <script src="/js/select2.full.min.js"></script>    <script src="/js/moment-with-locales.js"></script>    <script src="/js/pikaday.js"></script>    <script src="/js/pikaday.jquery.js"></script>    <script src="/js/popper.min.js"></script>    <script src="/js/bootstrap.min.js"></script>    <script src="/js/d3.v5.js"></script>    <script src="/js/dagre-d3.js"></script>    <script src="/js/myapp.js?ramd=2010716946"></script>
    </head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
    <a class="navbar-brand" href="An Internal Server Error Occurred
```

Which clearly shows, that the UrlHelper error occurs in both cases, however only in one of them, gets handled as internal server error, and in the others as 404 not-found.

**Comment by markstory** [comment]
If a route could not be matched the RoutingMiddleware will not set the request context. Your url filter should accomodate the case where the request is null.

Setting the request context before parsing routes would solve this specific scenario, but the general situation could still come up if exceptions are raised before routing middleware is called.

**Comment by smarek** [comment]
Ok, thank you @markstory , I've been using default filter to persist `lang` param, like this
```
Router::addUrlFilter(function ($params, \Cake\Http\ServerRequest $request) {
    if (!isset($params['lang'])) {
        if (!empty($request->getParam('lang'))) {
            $params['lang'] = $request->getParam('lang');
        } else {
            $params['lang'] = 'en_US';
        }
    }
    return $params;
});
```

Version which does not trigger the Internal Server Error looks like this
```
Router::addUrlFilter(/**
 * @param array $params
 * @param \Cake\Http\ServerRequest $request
 * @return array mixed
 */
    function ($params, $request) {
    if (!isset($params['lang'])) {
        if ($request && !empty($request->getParam('lang'))) {
            $params['lang'] = $request->getParam('lang');
        } else {
            $params['lang'] = 'en_US';
        }
    }
    return $params;
});
```

Also further in debugging, turns out, it's not about ServerRequest not being set, but URL generation in given context, without having router fallbacks will fail and thus rendering layout will fail in unpredictable ways.

However code above solves the un-predictable behavior, maybe some framework mitigation could be added, so this does not happen in future?

**Comment by markstory** [comment]
> However code above solves the un-predictable behavior, maybe some framework mitigation could be added, so this does not happen in future?

I don't think we can always ensure a request is set in the router context though. For example, if an exception is raised before the routing middleware is applied then we will also not be able to pass a request.

**Comment by smarek** [comment]
No, but I think you can handle exceptions in custom provided url filters gracefully, top line of the stacktrace says
```
2019-03-10 18:09:58 Error: [TypeError] Argument 2 passed to Cake\Http\BaseApplication::{closure}() must be an instance of Cake\Http\ServerRequest, null given, called in /var/www/myapp/vend
or/cakephp/cakephp/src/Routing/Router.php on line 589   
```
That is not very helpful in debugging, and could be handled by framework, and reported as issue with custom filter, or transform the filters to named filters, so the report can contain name (or store stacktrace of `public static function addUrlFilter(callable $function)` along the custom filter when debug is enabled)

**Comment by markstory** [comment]
>That is not very helpful in debugging, and could be handled by framework, and reported as issue with custom filter, or transform the filters to named filters, so the report can contain name...

Catching Errors updating the message to point out that a URL filter failed, and re-raising is something we could do.
