### ISSUE TITLE
Cake 4 - Baking fixture with -h throws an exception

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13128]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2

### What you did
I ran `bin/cake bake fixture -h`

### What happened
```
$ bin/cake bake fixture -h
Exception: strlen() expects parameter 1 to be string, int given in [/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php, line 175]
2019-04-17 09:48:02 Error: [TypeError] strlen() expects parameter 1 to be string, int given in /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php on line 175
Stack Trace:
#0 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php(175): strlen(1)
#1 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(173): Cake\Console\ConsoleInputOption->usage()
#2 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(97): Cake\Console\HelpFormatter->_generateUsage()
#3 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php(737): Cake\Console\HelpFormatter->text(72)
#4 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(197): Cake\Console\ConsoleOptionParser->help(NULL, 'text')
#5 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(173): Cake\Console\Command->displayHelp(Object(Cake\Console\ConsoleOptionParser), Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#6 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(161): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))
#7 /Users/davidyell/Sites/CakePHP4/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#8 {main}
```

### What you expected to happen
I thought that the options for the bake fixture command would be output. Such as record importing and count, etc.

### Notes
I realise that this might be better in `cakephp/bake`, but as the exception was thrown from the core I submitted it to this repo.

**Comment by davidyell** [comment]
Duplicates #13133

**Comment by davidyell** [comment]
Apologies, I didn't mean to close this one!

**Comment by saeideng** [comment]
this shows because int is not allowed here 

```php
        ])->addOption('count', [
            'help' => 'When using generated data, the number of records to include in the fixture(s).',
            'short' => 'n',
            'default' => 1, // <-- here
```

but we should accept it 

https://github.com/cakephp/bake/blob/e089022375be50d049fd90296dce2c20b9e5bc78/src/Command/FixtureCommand.php#L74
