### ISSUE TITLE
Access with url encoded backslashes (%5C) returns 500 error

### ISSUE THREAD

**Issue by sotawada** [cakephp/cakephp#13381]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.15
* Platform and Target: Apache, MySQL, GET access

### What you did
access with URL http://localhost:8888/%5C.
And also route doesn't have a url start with backslashes

### What happened
It returns error
```
2019-06-28 11:31:37 Error: Fatal Error (256): [Error] Class '\' not found
#0 /var/www/html/vendor/cakephp/cakephp/src/Datasource/ModelAwareTrait.php(112): Cake\ORM\Locator\TableLocator->get('\\')
#1 /var/www/html/vendor/k1low/property-enum/src/Controller/Component/AutoSetComponent.php(16): Cake\Controller\Controller->loadModel()
#2 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(353): PropertyEnum\Controller\Component\AutoSetComponent->startup(Object(Cake\Event\Event))
#3 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /var/www/html/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /var/www/html/vendor/cakephp/cakephp/src/Controller/Controller.php(675): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#6 /var/www/html/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(127): Cake\Controller\Controller->startupProcess()
#7 /var/www/html/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(91): Cake\Error\ExceptionRenderer->_getController()
#8 /var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(136): Cake\Error\ExceptionRenderer->__construct(Object(Cake\Error\FatalErrorException))
#9 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#10 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#11 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Class '...', '/var/www/html/v...', 180)
#12 /var/www/html/vendor/cakephp/debug_kit/config/bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Class '...', '/var/www/html/v...', 180, Array)
#13 [internal function]: Cake\Core\Plugin::{closure}(256, '[Error] Class '...', '/var/www/html/v...', 180, Array)
#14 /var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(180): trigger_error('[Error] Class '...', 256)
#15 /var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#16 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#17 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(177): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\PHP7ErrorException))
#18 [internal function]: Cake\Error\BaseErrorHandler->wrapAndHandleException(Object(Cake\Error\PHP7ErrorException))
#19 {main} in [/var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php, line 180]


2019-06-28 11:31:37 Error: Fatal Error (256): [Error] Class '\' not found
#0 /var/www/html/vendor/cakephp/cakephp/src/Datasource/ModelAwareTrait.php(112): Cake\ORM\Locator\TableLocator->get('\\')
#1 /var/www/html/vendor/k1low/property-enum/src/Controller/Component/AutoSetComponent.php(16): Cake\Controller\Controller->loadModel()
#2 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(353): PropertyEnum\Controller\Component\AutoSetComponent->startup(Object(Cake\Event\Event))
#3 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /var/www/html/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /var/www/html/vendor/cakephp/cakephp/src/Controller/Controller.php(675): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#6 /var/www/html/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(127): Cake\Controller\Controller->startupProcess()
#7 /var/www/html/vendor/cakephp in [/var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php, line 180]
```

### What you expected to happen
Expected to return 404 error

**Comment by rchavik** [comment]
Try turning of debug and retry.

**Comment by sotawada** [comment]
still returns 500 error
isn't supposed to return 404 error?

**Comment by markstory** [comment]
Looks like your application is using a component that is resulting in the `Cake\ORM\Locator\TableLocator->get('\\')` being called. You should look into the AutoSetComponent as it is next in the stacktrace.

**Comment by sotawada** [comment]
Thanks for your help rchavik and markstory 
Cakephp is absolutely alright and the problem was the component you mentioned  

Thanks again for your help guys!
