### ISSUE TITLE
Unable to catch Cake\Database\Exception\NestedTransactionRollbackException

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#13821]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.9 (1e89aa0399ce4c0f9af764e3b61aa24826278feb)
* Platform and Target: Ubuntu 18 + Apache FPM + MariaDb + PHP 7.2

### What you did

Saving data that violated a unique composite key:

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2020-01-23-60-REZ' for key 'property_accommodation_id_date_rate_code' []

### What happened

```
[Cake\Database\Exception\NestedTransactionRollbackException] Cannot commit transaction - rollback() has been already called in the nested transaction
#0 /var/www/foo/bar/vendor/cakephp/cakephp/src/Database/Connection.php(740): Cake\Database\Connection->rollback(false)
#1 /var/www/foo/bar/vendor/cakephp/cakephp/src/ORM/Table.php(1640): Cake\Database\Connection->transactional(Object(Closure))
#2 /var/www/foo/bar/vendor/cakephp/cakephp/src/ORM/Table.php(1926): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#3 /var/www/foo/bar/vendor/cakephp/cakephp/src/ORM/Table.php(2240): Cake\ORM\Table->save(Object(App\Model\Entity\PropertyAccommodationRate), Object(ArrayObject))
#4 /var/www/foo/bar/vendor/cakephp/cakephp/src/Database/Connection.php(738): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 /var/www/foo/bar/vendor/cakephp/cakephp/src/ORM/Table.php(2244): Cake\Database\Connection->transactional(Object(Closure))
#6 /var/www/foo/bar/src/Logic/InventoryLogic.php(58): Cake\ORM\Table->saveMany(Array)
#7 /var/www/foo/bar/src/Logic/BookingLogic.php(515): App\Logic\InventoryLogic->saveMany(60, Array, Array)
#8 /var/www/foo/bar/src/Logic/BookingLogic.php(481): App\Logic\BookingLogic->reduceInventory(35112, Object(Adapter\Service\Hotel\Room\Accommodation), Array)
#9 /var/www/foo/bar/src/Logic/BookingLogic.php(242): App\Logic\BookingLogic->rates(35112, 35120, Object(Adapter\Service\Hotel\Room\Accommodation), Object(Adapter\Service\Hotel\Room\Rate))
#10 /var/www/foo/bar/plugins/Api/src/Controller/BookController.php(60): App\Logic\BookingLogic->process(Object(Adapter\Service\Hotel\Property), Object(stdClass), Object(App\Model\Entity\Publisher))
#11 /var/www/foo/bar/vendor/cakephp/cakephp/src/Database/Connection.php(738): Api\Controller\BookController->Api\Controller\{closure}(Object(Cake\Database\Connection))
#12 /var/www/foo/bar/plugins/Api/src/Controller/BookController.php(82): Cake\Database\Connection->transactional(Object(Closure))
#13 /var/www/foo/bar/vendor/cakephp/cakephp/src/Controller/Controller.php(610): Api\Controller\BookController->reservation()
#14 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#15 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(Api\Controller\BookController))
#16 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /var/www/foo/bar/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 /var/www/foo/bar/vendor/dereuromark/cakephp-setup/src/Middleware/MaintenanceMiddleware.php(47): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): Setup\Middleware\MaintenanceMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#22 /var/www/foo/bar/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#24 /var/www/foo/bar/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 /var/www/foo/bar/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 /var/www/foo/bar/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#30 /var/www/foo/bar/webroot/index.php(40): Cake\Http\Server->run()
#31 {main}
Request URL: /publisher/v3.0/book/reservation.json
```

### What you expected to happen

I expect to be able to catch this exception, but when wrapping the offending saveMany operation in a try/catch block, nothing is caught.

```php
try {
    $result = $this->objPropertyAccommodationRateTable->saveMany($arrayToSave);
} catch(\Exception $e) {
    die('no catch?');
}
```

While I have resolved the true bug causing this, this particular operation is non-mission critical. I rather catch and log the issue, rather than it cratering the entire operation.

**Comment by markstory** [comment]
What do you think is making this exception uncatchable? It is a pretty simple exception subclass.

**Comment by othercorey** [comment]
This exception is caught in a unit test so there must be a reason your code isn't executing.

https://github.com/cakephp/cakephp/blob/61a1ff9672430456a7a261f053911cab93793742/tests/TestCase/Database/ConnectionTest.php#L1217-L1229

**Comment by ADmad** [comment]
@cnizzardini Are you able to provide a way to reproduce your issue or we should chalk this up as developer error?
