### ISSUE TITLE
DatabaseSession: duplicate primary key, integrity constraint violation

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14783]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1 stable composer
* Platform and Target: nginx 1.14.2, mysql 8.0.20, php 7.4.x

Pentester tries to tamper with sessions handling, probably switching cookies/csrf tokens between two user/browser sessions, error as follows
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'bac5vcxxxxxxxxxxul9e6a092' for key 'sessions.PRIMARY'

#0 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute()
#1 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Database/Connection.php(341): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(69): Cake\Database\Connection->Cake\Database\{closure}()
#3 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Database/Connection.php(344): Cake\Core\Retry\CommandRetry->run()
#4 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Database/Query.php(249): Cake\Database\Connection->run()
#5 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(2042): Cake\Database\Query->execute()
#6 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(1934): Cake\ORM\Table->_insert()
#7 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(1835): Cake\ORM\Table->_processSave()
#8 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(1535): Cake\ORM\Table->Cake\ORM\{closure}()
#9 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Database/Connection.php(691): Cake\ORM\Table->Cake\ORM\{closure}()
#10 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(1536): Cake\Database\Connection->transactional()
#11 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/ORM/Table.php(1836): Cake\ORM\Table->_executeTransaction()
#12 /var/www/app.domain.eu/src/Model/Table/AppTable.php(24): Cake\ORM\Table->save()
#13 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(158): App\Model\Table\AppTable->save()
#14 [internal function]: Cake\Http\Session\DatabaseSession->write()
#15 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Http/Session.php(387): session_write_close()
#16 /var/www/app.domain.eu/vendor/cakephp/cakephp/src/Http/Server.php(93): Cake\Http\Session->close()
#17 /var/www/app.domain.eu/webroot/index.php(40): Cake\Http\Server->run()
#18 {main}

```

Model Sessions created as follows
```sql
CREATE TABLE `sessions` (
 `id` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `user_id` int DEFAULT NULL,
 `created` datetime DEFAULT CURRENT_TIMESTAMP,
 `modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `data` blob,
 `expires` int unsigned DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `user_id` (`user_id`),
 CONSTRAINT `sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

Not sure whats going on, request obviously fails, preventing further penetration, however i'm not sure if fail is intentional, or if the DatabaseSession should be able to recover from this automatically

Also, from time to time, I see as **session ID**, ordinary attack payloads, such as **`../../etc/passwd`** and similar, and i'd expect session id name to be strictly validated and server-generated, which means, it should not automatically create session anywhere, if the ID is not previously known to session storage

**Comment by markstory** [comment]
CakePHP enables [strict sessions](https://www.php.net/manual/en/session.configuration.php#ini.session.use-strict-mode) which aims to help prevent this but not all situations can be prevented with this setting.

It sounds like your pentester was attempt to hijack sessions and they were not successful? While the integrity error isn't the ideal error message what are you hoping to see instead? I don't think the session should be persisted and the storage adapter can't change the session ID at that point. Our only real option is to fail the request.

**Comment by smarek** [comment]
I already had the use_strict_mode set in php.ini of webserver, maybe duplicated check, but better be safe than sorry.

Also I don't know any details, but it seems like the only protection here is the PRIMARY/UNIQUE setting of database column, and that the situation is not handled gracefully, ie. by emitting event that would fail with some meaningful error or re-generate the session id instead of failing on DB column uniqueness, because this can happen as well if the session ID generator generates duplicated session ID, and such situation should be handled gracefully as well

And the last thing, the faked Session ID i mention in the end of my submission here, if the ID is validated, it bypassed the validation, because it contains characters not common/expected in session ID, if it's not validated, app clearly persists user-provided session ID without further checks, and I'm not sure how this was achieved

**Comment by markstory** [comment]
> And the last thing, the faked Session ID i mention in the end of my submission here, if the ID is validated, it bypassed the validation, because it contains characters not common/expected in session ID, if it's not validated, app clearly persists user-provided session ID without further checks, and I'm not sure how this was achieved

What would constitute session id validation? We don't currently do any as it is not really possible to tell an invalid session id from a valid one.

**Comment by smarek** [comment]
Reading the docs https://www.php.net/manual/en/function.session-id.php#116836 and specifically the first comment from Riikka K., this should be possible
Also `session.sid_length` allows you to set identifier up-to 256 characters
https://www.php.net/manual/en/session.configuration.php#ini.session.sid-length

Secondly, i've just tried, and currently see no harm possible done, but simply by editing the session cookie value to anything, the app currently stores the user-provided string in DB, and that seems plain wrong to me

**Comment by markstory** [comment]
> Secondly, i've just tried, and currently see no harm possible done, but simply by editing the session cookie value to anything, the app currently stores the user-provided string in DB, and that seems plain wrong to me

Ok. To my understanding that is how sessions work in PHP. If you can find a way around that we can try and make changes.

**Comment by othercorey** [comment]
I don't think we should rely on php source as documentation because there is no guarantee between releases.

However, we could validate length and and character range based on the ini settings.

**Comment by smarek** [comment]
@othercorey custom session id should be imho validated exactly as you proposed, based on ini settings. the validator and the settings shall reside in app configuration or in session/cookie handler interface

**Comment by othercorey** [comment]
> @othercorey custom session id should be imho validated exactly as you proposed, based on ini settings. the validator and the settings shall reside in app configuration or in session/cookie handler interface

If I understand correctly, it will validate character ranges, but the ini configuration is for generating session ids.

**Comment by smarek** [comment]
Well, looking at the sources, i'd say we can validate both characters used and length, specifically

  - alphabet https://github.com/php/php-src/blob/master/ext/session/session.c#L259
  - min length https://github.com/php/php-src/blob/master/ext/session/session.c#L734
  - max length https://github.com/php/php-src/blob/master/ext/session/session.c#L76
  - internal validator https://github.com/php/php-src/blob/master/ext/session/session.c#L330

And yes, the ini configuration is for expected length, and I also think the level of (dis)trust in user-provided session-id value could be configurable (for compatibility), the same way we can opt-in for different csrf/cookie/etc.. protections

**Comment by paulrwest** [comment]
Any update on this issue? I am also seeing this error in my logs quite regularly, it's hard to tell but the error seems to happen with regular usage of my site. Is there any way I can gather more info or catch this better myself? I noticed the milestone keeps moving how likely will this be in 4.2?

-  CakePHP: "4.1.7"
-  PHP: "7.4.16"
-  Apache: "2.4.29" (Ubuntu)

````
[PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'amm8bbgd1knhitphvu1554lcjj' for key 'PRIMARY' in /var/www/site/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
- /var/www/site/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
- /var/www/site/vendor/cakephp/cakephp/src/Database/Connection.php:341
- /var/www/site/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- /var/www/site/vendor/cakephp/cakephp/src/Database/Connection.php:344
- /var/www/site/vendor/cakephp/cakephp/src/Database/Query.php:249
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:2046
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:1938
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:1839
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:1539
- /var/www/site/vendor/cakephp/cakephp/src/Database/Connection.php:691
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:1540
- /var/www/site/vendor/cakephp/cakephp/src/ORM/Table.php:1840
- /var/www/site/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php:158
- session_write_close - [internal], line ??- /var/www/site/vendor/cakephp/cakephp/src/Http/Session.php:387
- /var/www/site/vendor/cakephp/cakephp/src/Http/Server.php:93
- /var/www/site/webroot/index.php:40
````

**Comment by markstory** [comment]
>  I noticed the milestone keeps moving how likely will this be in 4.2?

The milestone moves as we do releases. Right now there isn't a way to reproduce this issue reliably so progress is unlikely.

**Comment by smarek** [comment]
@paulrwest would be great, if you could find out how to reproduce the issue, so we could debug the culprit and fix this. Also is your frontend standard CakePHP generated, or do you use some kind of JS frontend (Vue/React/etc...) ? And "quite regularly" means what, once a day or week or month?

**Comment by paulrwest** [comment]
@smarek struggling to reproduce but for now it's happening about once a day on a web-app with only about 1k log-ins a day. Frontend is just cake with minimal jquery. the referrer URL is always a page behind authentication so the user was already logged in with a session (session may have expired though) as often I see it logged on a user being redirected back to login but not always.

**Comment by alexvanniel** [comment]
I would like to contribute to this issue a little, or at least make it known that others are also experiencing this. We are seeing these integrity errors as well. I have been trying to figure out how and if I can reproduce this but unfortunately I have also been unsuccessfull in reproducing. It does seem to happen only on AJAX related calls. Usually for users that are or have been authenticated. I have not been able to figure out if this is caused because the session has expired or that the same session is created twice because the AJAX calls is done at the same time as some other request. Sometimes the integrity error happens once a day and sometimes multiple times a day. This is with CakePHP 4.3.1 by the way.

**Comment by markstory** [comment]
@alexvanniel If you figure out a patch to handle the integrity errors more gracefully that would be great. I don't think there is a way to entirely avoid them though.

**Comment by alexvanniel** [comment]
> @alexvanniel If you figure out a patch to handle the integrity errors more gracefully that would be great. I don't think there is a way to entirely avoid them though.

I will have a look at this next week. It would be a start to know why this actually happens. I have not been able to put my finger on it.

**Comment by paulrwest** [comment]
I've just detected something that could be connected to this problem. My live sessions table is huge! I don't think cakephp is clearing out the session table correctly. My application gets about 60,000 logins a month but surely there shouldn't be over 1.5 million rows in the table?

mysql> select count(*) as count from sessions;
+---------+
| count   |
+---------+
| 1528679 |
+---------+
1 row in set (24.92 sec)

Is this a user configuration issue or something incorrect with cakePHP? this issue was present in both v3 and v4.

**Comment by ndm2** [comment]
From what I've seen it's often people's PHP config. CakePHP's session handlers do not decide to do any cleanup on their own, instead they depend on PHP to instruct them do so, which in turn depends on how PHP's session garbage collection is configured.

Check your [`session.gc_probability`](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-probability),  [`session.gc_divisor`](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-divisor) and [`session.gc_maxlifetime`](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime) configuration.

**Comment by paulrwest** [comment]
Thank you this is exactly my issue, gc_probability is set to 0. You saved me a lot of time debugging. Now to work out why my docker image has it set to this rather than default:

session.gc_divisor | 1000
session.gc_maxlifetime | 3600
session.gc_probability | 0

**Comment by paulrwest** [comment]
I would suggest others on this issue check the same values as it would explain why we are seeing the error so often.

**Comment by alexvanniel** [comment]
It is however a bit unclear to me as to what these settings should be set at. Should gc_probability set to 1 and why does nearly every production configuration I see have this set to 0? Does Cake have a command that can be run like Symfony has to start GC on the session?

**Comment by othercorey** [comment]
Please open a new issue if there is a new request or bug.

**Comment by paulrwest** [comment]
_Some distributions (Debian, and thus Ubuntu) opt into using their own session garbage collector. Implementing an alternative session garbage collector implies disabling the default SGC by setting session.gc_probability to 0._ ([source](https://www.getpagespeed.com/server-setup/php/cleanup-php-sessions-like-a-pro))

Any PHP installation running on ubuntu will have this value set to 0 if they have not set it themselves. I'm currently investigating the best solution to determine if this is a 'bug' or needs a request.
