### ISSUE TITLE
Unable to configure the session, setting session.cookie_samesite failed.

### ISSUE THREAD

**Issue by chyt** [cakephp/cakephp#15009]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.4
* Platform and Target: Development server, Apache/MySQL/PHP 7.2 on OS X 10.15.6

### What you did
I'm trying to set the `session.cookie_samesite` configuration:

```
    'Session' => [
        'defaults' => 'database',
        'timeout' => 525600,
        'ini' => [
            'session.cookie_lifetime' => 525600,
            'session.cookie_samesite' => 'None',
            'session.cookie_secure' => true,
        ],
    ],
```

### What happened

I get the following error:

```
Fatal error: [RuntimeException] Unable to configure the session, setting session.cookie_samesite failed. (/Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Http/Session.php:321) #0 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Http/Session.php(228): Cake\Http\Session->options(Array) #1 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Http/Session.php(127): Cake\Http\Session->__construct(Array) #2 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Http/ServerRequestFactory.php(71): Cake\Http\Session::create(Array) #3 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(125): Cake\Http\ServerRequestFactory::fromGlobals() #4 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(106): Cake\Error\ExceptionRenderer->_getController() #5 /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(169): Cake\Error\ExceptionRenderer->__construct(Object(Cake\Error\ in /Users/cyt/Github/watch-price-tracker/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
```

**Comment by markstory** [comment]
PHP 7.2 doesn't support samesite attributes. You need to upgrade to 7.3 to get samesite cookie attribute support. CakePHP only currently emulates samesite attributes for cookies added to responses by controllers.

**Comment by chyt** [comment]
Thanks, upgraded to 7.3 and that solved the problem.
