### ISSUE TITLE
Enabling FormProtection causes all POST tests to fail

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16918]
This can be reproduced on cakephp/app application template:
1) Create new [cakephp/app](https://github.com/cakephp/app)
2) if you run `vendor/bin/phpunit --filter testCsrfAppliedOk` test will pass
3) now enable FormProtection component by uncommenting following line:
https://github.com/cakephp/app/blob/4.x/src/Controller/AppController.php#L51
4) if you run `vendor/bin/phpunit --filter testCsrfAppliedOk` test will now fail with following error:
```
F                                                                   1 / 1 (100%)

Time: 00:00.161, Memory: 22.00 MB

There was 1 failure:

1) App\Test\TestCase\Controller\PagesControllerTest::testCsrfAppliedOk
Possibly related to Cake\Http\Exception\BadRequestException: "`_Token` was not found in request data."
#0 /application/vendor/cakephp/cakephp/src/Controller/Component/FormProtectionComponent.php(97): Cake\Controller\Component\FormProtectionComponent->validationFailure(Object(Cake\Form\FormProtector))
#1 /application/vendor/cakephp/cakephp/src/Event/EventManager.php(309): Cake\Controller\Component\FormProtectionComponent->startup(Object(Cake\Event\Event))
#2 /application/vendor/cakephp/cakephp/src/Event/EventManager.php(286): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#3 /application/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(92): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#4 /application/vendor/cakephp/cakephp/src/Controller/Controller.php(648): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#5 /application/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php(129): Cake\Controller\Controller->startupProcess()
#6 /application/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php(114): Cake\Controller\ControllerFactory->handle(Object(Cake\Http\ServerRequest))
#7 /application/vendor/cakephp/cakephp/src/Http/BaseApplication.php(320): Cake\Controller\ControllerFactory->invoke(Object(MainWebsite\Controller\PagesController))
#8 /application/vendor/cakephp/cakephp/src/Http/Runner.php(77): Cake\Http\BaseApplication->handle(Object(Cake\Http\ServerRequest))
#9 /application/vendor/cakephp/cakephp/src/I18n/Middleware/LocaleSelectorMiddleware.php(61): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#10 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\I18n\Middleware\LocaleSelectorMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#11 /application/vendor/muffin/footprint/src/Middleware/FootprintMiddleware.php(50): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#12 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Muffin\Footprint\Middleware\FootprintMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#13 /application/vendor/cakephp/authorization/src/Middleware/RequestAuthorizationMiddleware.php(102): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#14 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Authorization\Middleware\RequestAuthorizationMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#15 /application/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php(129): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#16 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Authorization\Middleware\AuthorizationMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#17 /application/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php(124): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#18 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Authentication\Middleware\AuthenticationMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#19 /application/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(174): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#20 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Http\Middleware\CsrfProtectionMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#21 /application/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php(162): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#22 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Http\Middleware\BodyParserMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#23 /application/src/Middleware/RedirectLoopProtectMiddleware.php(26): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#24 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): App\Middleware\RedirectLoopProtectMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#25 /application/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(186): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#26 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Routing\Middleware\RoutingMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#27 /application/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(68): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#28 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Routing\Middleware\AssetMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#29 /application/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(131): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#30 /application/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Error\Middleware\ErrorHandlerMiddleware->process(Object(Cake\Http\ServerRequest), Object(Cake\Http\Runner))
#31 /application/vendor/cakephp/cakephp/src/Http/Runner.php(58): Cake\Http\Runner->handle(Object(Cake\Http\ServerRequest))
#32 /application/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(App\Application))
#33 /application/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php(141): Cake\Http\Server->run(Object(Cake\Http\ServerRequest))
#34 /application/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(478): Cake\TestSuite\MiddlewareDispatcher->execute(Array)
#35 /application/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(380): App\Test\TestCase\Controller\PagesControllerTest->_sendRequest('/pages/home', 'POST', Array)
#36 /application/tests/TestCase/Controller/PagesControllerTest.php(103): App\Test\TestCase\Controller\PagesControllerTest->post('/pages/home', Array)
#37 /application/vendor/phpunit/phpunit/src/Framework/TestCase.php(1548): App\Test\TestCase\Controller\PagesControllerTest->testCsrfAppliedOk()
#38 /application/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): PHPUnit\Framework\TestCase->runTest()
#39 /application/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#40 /application/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\PagesControllerTest))
#41 /application/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#42 /application/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#43 /application/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#44 /application/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(661): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#45 /application/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#46 /application/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#47 /application/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#48 /application/vendor/bin/phpunit(123): include('/application/ve...')
#49 {main}

Failed asserting that 'CSRF' is not in response body.

/application/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:1049
/application/tests/TestCase/Controller/PagesControllerTest.php:106

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
```

### CakePHP Version

4.4.8

### PHP Version

8.1

**Comment by garas** [comment]
You should add `$this->enableSecurityToken()` to tests.

https://book.cakephp.org/4/en/development/testing.html#testing-actions-protected-by-csrfcomponent-or-securitycomponent
