### ISSUE TITLE
4.x: Param Type Bug in Mailer

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17250]
### Description

```
TypeError: Cake\Mailer\Message::validateEmail(): Argument #1 ($email) must be of type string, null given, called in app/vendor/cakephp/cakephp/src/Mailer/Message.php on line 692
#0 app/vendor/cakephp/cakephp/src/Mailer/Message.php(692): Cake\Mailer\Message->validateEmail()
#1 app/vendor/cakephp/cakephp/src/Mailer/Message.php(475): Cake\Mailer\Message->setEmail()
#2 app/vendor/dereuromark/cakephp-tools/src/Mailer/Mailer.php(61): Cake\Mailer\Message->setTo()
#3 app/src/Queue/Task/RegistrationMailTask.php(44): Tools\Mailer\Mailer->__call()
#4 app/vendor/dereuromark/cakephp-queue/src/Queue/Processor.php(216): App\Queue\Task\RegistrationMailTask->run()
#5 app/vendor/dereuromark/cakephp-queue/src/Queue/Processor.php(164): Queue\Queue\Processor->runJob()
#6 app/vendor/dereuromark/cakephp-queue/src/Command/RunCommand.php(110): Queue\Queue\Processor->run()
#7 app/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Queue\Command\RunCommand->execute()
#8 app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Cake\Console\BaseCommand->run()
#9 app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand()
#10 app/bin/cake.php(12): Cake\Console\CommandRunner->run()
```

This seems to happen as

    return $this->setEmail('to', $email, $name);
    
$name can still be null, but furtheron setEmail() with

    $this->validateEmail($email, $varName);
    
requires already not null silently, and furthermore

    protected function validateEmail(string $email, string $context): void
    
then blows up.

### CakePHP Version

4.4

### PHP Version

8.1

**Comment by dereuromark** [comment]
Apprently, there must be sth else going on, I will recheck.
