### ISSUE TITLE
Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(): Argument #3 ($endPointer) must be of type int, null given

### ISSUE THREAD

**Issue by GBeushausen** [cakephp/cakephp#17258]
### Description

Hi,

i'm developing an application using CakePHP4. When generating a template for viewing a database Table that has a nullable field in it, phpcs quits with a fatal error.

This line is causing the issue:

`<td><?= $pricelist->default_price === null ? '' : $this->Number->format($pricelist->default_price) ?></td>`

This is the error message:

```
Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(): Argument #3 ($endPointer) must be of type int, null given, called in /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php on line 179 and defined in /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/IdentificatorHelper.php:29
Stack trace: 
#0 /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php(179): SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(Object(PHP_CodeSniffer\Files\LocalFile), 358, NULL) 
#1 /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php(52): SlevomatCodingStandard\Sniffs\ControlStructures\RequireNullCoalesceOperatorSniff->checkIdenticalOperator(Object(PHP_CodeSniffer\Files\LocalFile), 348) 
#2 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\ControlStructures\RequireNullCoalesceOperatorSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 348) 
#3 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process() 
#4 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(632): PHP_CodeSniffer\Files\LocalFile->process() 
#5 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(438): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile)) 
#6 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(116): PHP_CodeSniffer\Runner->run() 
#7 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS() 
```

If i change the code to this, it wouldn't cause phpcs to fail:

```php
<td><?= $pricelist->default_price == null ? '' : $this->Number->format($pricelist->default_price) ?></td>
```

### CakePHP Version

4.4.17

### PHP Version

8.1

**Comment by markstory** [comment]
What version of phpcs are you using? Are you using the cakephp coding standard or a different ruleset?

**Comment by GBeushausen** [comment]
I'm using phpcs 3.7.2. I use the standard phpcs.xml that comes with CakePHP.

**Comment by markstory** [comment]
I've not been able to reproduce this fatal error. I used the following template

```php
<?php
/**
 * @var \App\View\AppView $this
 * @var iterable<\App\Model\Entity\Product> $products
 */
?>
<div class="products index content">
    <?= $this->Html->link(__('New Product'), ['action' => 'add'], ['class' => 'button float-right']) ?>
    <h3><?= __('Products') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id') ?></th>
                    <th><?= $this->Paginator->sort('name') ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product): ?>
                <tr>
                    <td><?= $this->Number->format($product->id) ?></td>
                    <td><?= $product->user_id === null ? '' : $this->Number->format($product->user_id) ?></td>
                    <td><?= h($product->name) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('View'), ['action' => 'view', $product->id]) ?>
                        <?= $this->Html->link(__('Edit'), ['action' => 'edit', $product->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $product->id], ['confirm' => __('Are you sure you want to delete # {0}?', $product->id)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>
```

My entity is defined as 

```php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Product Entity
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $name
 *
 * @property \App\Model\Entity\Product[] $linked_products
 */
class Product extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array<string, bool>
     */
    protected $_accessible = [
        'name' => true,
        'user_id' => true,
        'linked_products' => true,
    ];
}
```

Running `phpcs` on this template like `vendor/bin/phpcs --standard=./phpcs.xml templates/Products/index.php` doesn't show a fatal error.

**Comment by ADmad** [comment]
Closing as unreproducible.
