### ISSUE TITLE
Cannot bake ControllerTest with non-table model

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#17332]
### Description

Steps to reproduce:
1) Create any controller with non-table model
```php
class NbpRatesController extends AppController
{
    public $modelClass = 'NbpApi.NbpRates';
    public $_modelType = 'Endpoint';
  
   //some other code
}
```
2) bake unit test for that controller

```
application@d6af9a97ebb9:/application$ bin/cake bake test Controller --prefix=Admin --plugin=SuperAdmin NbpRates
Bake is detecting possible fixtures...

2023-10-05 16:33:22 error: [TypeError] Bake\Command\TestCommand::_processModel(): Argument #1 ($subject) must be of type Cake\ORM\Table, NbpApi\Model\Endpoint\NbpRatesEndpoint given, called in /application/vendor/cakephp/bake/src/Command/TestCommand.php on line 502 in /application/vendor/cakephp/bake/src/Command/TestCommand.php on line 465
Stack Trace:
- /application/vendor/cakephp/bake/src/Command/TestCommand.php:502
- /application/vendor/cakephp/bake/src/Command/TestCommand.php:452
- /application/vendor/cakephp/bake/src/Command/TestCommand.php:258
- /application/vendor/cakephp/bake/src/Command/TestCommand.php:132
- /application/vendor/cakephp/cakephp/src/Console/BaseCommand.php:189
- /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /application/bin/cake.php:12

[TypeError] Bake\Command\TestCommand::_processModel(): Argument #1 ($subject) must be of type Cake\ORM\Table, NbpApi\Model\Endpoint\NbpRatesEndpoint given, called in /application/vendor/cakephp/bake/src/Command/TestCommand.php on line 502 in /application/vendor/cakephp/bake/src/Command/TestCommand.php on line 465

Stack Trace:

#0 /application/vendor/cakephp/bake/src/Command/TestCommand.php(502): Bake\Command\TestCommand->_processModel(Object(NbpApi\Model\Endpoint\NbpRatesEndpoint))
#1 /application/vendor/cakephp/bake/src/Command/TestCommand.php(452): Bake\Command\TestCommand->_processController(Object(SuperAdmin\Controller\Admin\NbpRatesController))
#2 /application/vendor/cakephp/bake/src/Command/TestCommand.php(258): Bake\Command\TestCommand->generateFixtureList(Object(SuperAdmin\Controller\Admin\NbpRatesController))
#3 /application/vendor/cakephp/bake/src/Command/TestCommand.php(132): Bake\Command\TestCommand->bake('Controller', 'NbpRates', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#4 /application/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Bake\Command\TestCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#5 /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Cake\Console\BaseCommand->run(Array, Object(Cake\Console\ConsoleIo))
#6 /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand(Object(Bake\Command\TestCommand), Array, Object(Cake\Console\ConsoleIo))
#7 /application/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#8 {main}
```

### CakePHP Version

4.4.17

### PHP Version

8.1

**Comment by dereuromark** [comment]
Side note:

    protected ?string $modelClass = null;

those are both protected ones
but this wouldnt directly be related to the issue of course.
