### ISSUE TITLE
2.6: Notice Error: Uninitialized string offset: 1020 in [.../lib/Cake/Network/Email/CakeEmail.php, line 1424]

### ISSUE THREAD

**Issue by mfn** [cakephp/cakephp#5948]
This notice is triggered with especially long lines stemming from email templates.

Shortest reproducible script:

`app/Console/Command/TriggerCakeEmailBugShell.php`:
```PHP
<?php
App::uses('CakeEmail', 'Network/Email');
App::uses('AppShell', 'Console/Command');
class TriggerCakeEmailBugShell extends \AppShell {
  public function trigger() {
    $email = new CakeEmail();
    $email->from(['from@example.com' => 'from@example.com']);
    $email->template('test');
    $email->emailFormat('html');
    $email->to(['to@example.com' => 'to@example.com']);
    $email->send();
  }
}
```

A file containing HTML-like content in a long line, >= 998 (\CakeEmail::LINE_LENGTH_MUST)
`app/View/Emails/html/test.ctp`:
```
<a>34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567
```

How to reproduce (please ignore the "sendmail not found" error, it's unrelated):
```
$ app/Console/cake trigger_cake_email_bug trigger
Notice Error: Uninitialized string offset: 1020 in [.../lib/Cake/Network/Email/CakeEmail.php, line 1424]

sh: 1: /usr/sbin/sendmail: not found
Error:
#0 .../lib/Cake/Network/Email/MailTransport.php(51): MailTransport->_mail('to@example.com', '', '<!DOCTYPE html ...', 'From: from@exam...', NULL)
#1 .../lib/Cake/Network/Email/CakeEmail.php(1161): MailTransport->send(Object(CakeEmail))
#2 .../app/Console/Command/TriggerCakeEmailBugShell.php(11): CakeEmail->send()
#3 .../lib/Cake/Console/Shell.php(444): TriggerCakeEmailBugShell->trigger()
#4 .../lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand('trigger', Array)
#5 .../lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 .../app/Console/cake.php(37): ShellDispatcher::run(Array)
#7 {main}
```

**Comment by markstory** [comment]
Pull request up #5954
