### ISSUE TITLE
[3.1] Strange (maybe faulty?) behaviour with contain().

### ISSUE THREAD

**Issue by RaXaR** [cakephp/cakephp#7591]
Hi there :)
 I am having a strange issue with contain() and not sure about the cause.

The DB: http://pastebin.com/HCxUVtS9
The AssessmentsTable: http://pastebin.com/CYfFnd2e
The CustomersTable: http://pastebin.com/Hvk5fRQm

In summary, I have Assessments belongsTo Customers belongstTo Companies belongsTo Groups.

In CustomersTable::getBaseQuery() everything works fine, but in Assessments::getBaseQuery() I get an erorr that reads: "Assessments is not associated with Companies".

I am not aware that I am trying to join Companies to Assessments anywhere???

PHP 5.4.25
Apache: 2.2.22
MySQL: 5.5.24

Any assistance would be great.

**Comment by lorenzo** [comment]
What is the stack trace for the error?

**Comment by RaXaR** [comment]
um, not sure how to send you the stacktrace? I've attached a screenshot so long.
![2015-10-21_151437](https://cloud.githubusercontent.com/assets/216180/10637582/c94477b0-7806-11e5-9236-48513c593d1e.jpg)

**Comment by RaXaR** [comment]
Um not sure how to send a stacktrace?, sending a screen shot so long:
![2015-10-21_151911](https://cloud.githubusercontent.com/assets/216180/10637680/35a8fcbe-7807-11e5-80a5-303243f71692.jpg)

**Comment by RaXaR** [comment]
Here's the stackTrace from error.log:
```
2015-10-21 13:18:57 Error: [InvalidArgumentException] Assessments is not associated with Companies
Request URL: /cakephp.tests/gtest001/assessments/index
Stack Trace:
#0 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(250): Cake\ORM\EagerLoader->_normalizeContain(Object(App\Model\Table\AssessmentsTable), 'Companies', Array, Array)
#1 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(358): Cake\ORM\EagerLoader->normalized(Object(App\Model\Table\AssessmentsTable))
#2 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(378): Cake\ORM\EagerLoader->attachableAssociations(Object(App\Model\Table\AssessmentsTable))
#3 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(538): Cake\ORM\EagerLoader->externalAssociations(Object(App\Model\Table\AssessmentsTable))
#4 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\Query.php(847): Cake\ORM\EagerLoader->loadExternal(Object(Cake\ORM\Query), Object(Cake\Database\Log\LoggingStatement))
#5 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#6 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\ORM\Query.php(798): Cake\ORM\Query->_all()
#7 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(288): Cake\ORM\Query->all()
#8 C:\wamp\www\cakephp.tests\gtest001\src\Model\Table\AssessmentsTable.php(147): Cake\ORM\Query->toArray()
#9 C:\wamp\www\cakephp.tests\gtest001\src\Controller\AssessmentsController.php(21): App\Model\Table\AssessmentsTable->getBaseQuery()
#10 [internal function]: App\Controller\AssessmentsController->index()
#11 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#12 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#13 C:\wamp\www\cakephp.tests\gtest001\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\AssessmentsController))
#14 C:\wamp\www\cakephp.tests\gtest001\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#15 {main}
```
