### ISSUE TITLE
belongsToMany [condition]s can't (always) utilize fields from the glue table.

### ISSUE THREAD

**Issue by beporter** [cakephp/cakephp#7707]
Seems like I've encountered another form of the bug from #7626 again (the "inverse" of it, this time?), by attempting to query _through_ the associated tables. For example:

**DB Schema:**
```sql
CREATE TABLE `posts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `body` text NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Glue table
CREATE TABLE `posts_tags` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(11) unsigned NOT NULL,
  `tag_id` int(11) unsigned NOT NULL,
  `is_hidden` tinyint(1) unsigned NOT NULL DEFAULT '0'
    COMMENT 'Allow internal association of a Post to Tags,
             but do not display this particular association publicly.',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tags` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```

**PostsTable:**
```php
// Define the default association with public page rendering in mind.
$this->belongsToMany('Tags', [
	'foreignKey' => 'post_id',
	'targetForeignKey' => 'tag_id',
	'through' => 'PostsTags',
	'conditions' => [
		'PostsTags.is_hidden' => false, // Suppress "hidden" Tags by default.
	],
]);
```

**PostsController:**
```php
// Grab all available Tags to generate
// a multi-select for assigning Tags to a Post.
$tags = $this->Posts->Tags->find('all');
```

The above will trigger an "unknown column" error, very similar to my report in #7626. My thinking is that loading the secondary table _through_ the association triggers the conditions from that association, but doesn't actually `JOIN` the "middle" table into the query (which is required in order to support the contents of the association's `[conditions]`). 

**Example exception:**
```
PDOException
SQLSTATE[42S22]: Column not found: 1054
 Unknown column 'PostsTags.is_hidden' in 'where clause'
```

**Example executed SQL**:
```sql
-- (PostsTags is used in the WHERE but not present in the FROM)
SELECT
  Tags.id AS `Tags__id`,
  Tags.name AS `Tags__name`
FROM
  tags Tags
WHERE
  PostsTags.is_hidden = :c0
```

**Example stack trace:**
```
#0  ROOT/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(36): PDOStatement->execute(NULL)
#1  ROOT/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2  ROOT/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3  ROOT/vendor/cakephp/cakephp/src/Database/Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4  ROOT/vendor/cakephp/cakephp/src/Database/Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5  ROOT/vendor/cakephp/cakephp/src/ORM/Query.php(872): Cake\Database\Query->execute()
#6  ROOT/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(272): Cake\ORM\Query->_execute()
#7  ROOT/vendor/cakephp/cakephp/src/ORM/Query.php(823): Cake\ORM\Query->_all()
#8  ROOT/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(448): Cake\ORM\Query->all()
#9  ROOT/vendor/cakephp/cakephp/src/ORM/Query.php(1004): Cake\ORM\Query->_call('map', Array)
#10 ROOT/src/Template/Posts/add_fields.ctp(17): Cake\ORM\Query->__call('map', Array)
#11 ROOT/src/Template/Posts/add_fields.ctp(17): Cake\ORM\Query->map(Object(Closure))
#12 ROOT/vendor/cakephp/cakephp/src/View/View.php(971): include('ROOT/src/Te...')
#13 ROOT/vendor/cakephp/cakephp/src/View/View.php(931): Cake\View\View->_evaluate('ROOT/src/Te...', Array)
#14 ROOT/vendor/cakephp/cakephp/src/View/View.php(1308): Cake\View\View->_render('ROOT/src/Te...', Array)
#15 ROOT/vendor/cakephp/cakephp/src/View/View.php(485): Cake\View\View->_renderElement('ROOT/src/Te...', Array, Array)
#16 ROOT/src/Template/Posts/add.ctp(32): Cake\View\View->element('Posts/a...', Array)
#17 ROOT/vendor/cakephp/cakephp/src/View/View.php(971): include('ROOT/src/Te...')
#18 ROOT/vendor/cakephp/cakephp/src/View/View.php(931): Cake\View\View->_evaluate('ROOT/src/Te...', Array)
#19 ROOT/vendor/cakephp/cakephp/src/View/View.php(579): Cake\View\View->_render('ROOT/src/Te...')
#20 ROOT/vendor/cakephp/cakephp/src/Controller/Controller.php(611): Cake\View\View->render(NULL, NULL)
#21 ROOT/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(120): Cake\Controller\Controller->render()
#22 ROOT/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PostsController))
#23 ROOT/webroot/index.php(38): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#24 {main}
```

---

The workaround isn't difficult, but not exactly ideal:

**PostsController:**
```php
// Avoids the association that includes the `[condition]` on the glue table.
$Tags = TableRegistry::get('Tags');
$tags = $Tags->find('all');
```

...I guess depending on your perspective (whether you wrote the ORM or whether you're a consumer of it) this might seem like "expected behavior"?

**Comment by markstory** [comment]
I wouldn't want to _always_ include the junction table in the association queries. However, if the association has non-empty conditions, we could contain() the junction table.

**Comment by beporter** [comment]
Oh sure I definitely agree on that. I've tried tracing the code, and I think the problem is going to be _where_ exactly to add the `contain()`. If I had a good suggestion, I'd offer a PR like last time, but I'm stumped right now. Any suggestions on where to look?

**Comment by markstory** [comment]
I would probably start by overloading `BelongsToMany::find()`.

**Comment by markstory** [comment]
Pull request up now.

**Comment by beporter** [comment]
@markstory How do you work a full time job, have a family and still get PRs done here? I suspect you may be a machine. Either way, consider me impressed. And thanks for the fix.

**Comment by AD7six** [comment]
@beporter there are actually 4 of him hyperthreaded =)

**Comment by beporter** [comment]
lol. That's a trick I wouldn't mind learning.

**Comment by markstory** [comment]
Instead of watching t.v/playing video games/sleeping, I 'play' on open source projects :smile:

**Comment by beporter** [comment]
I wish I had time to do those things too! I'm life-ing wrong, clearly.
