### ISSUE TITLE
Method integer does not exist

### ISSUE THREAD

**Issue by Zehir** [cakephp/cakephp#8286]
Hello,

since last update or more, when I use the bake pages I get this error;

Cakephp Version: 3.2.2
PHP_VERSION:7.0.3-5+deb.sury.org~trusty+1

Stacktrace:
```
2016-02-18 12:24:04 Error: [ReflectionException] Method integer does not exist
Request URL: /users/edit/35
Referer URL: https://local.dev/users/edit/35
Stack Trace:
#0 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Validation/RulesProvider.php(70): ReflectionClass->getMethod('integer')
#1 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Validation/ValidationRule.php(140): Cake\Validation\RulesProvider->__call('integer', Array)
#2 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Validation/Validator.php(1410): Cake\Validation\ValidationRule->process(35, Array, Array)
#3 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Validation/Validator.php(137): Cake\Validation\Validator->_processRules('id', Object(Cake\Validation\ValidationSet), Array, false)
#4 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/ORM/Marshaller.php(193): Cake\Validation\Validator->errors(Array, false)
#5 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/ORM/Marshaller.php(466): Cake\ORM\Marshaller->_validate(Array, Array, false)
#6 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/ORM/Table.php(2055): Cake\ORM\Marshaller->merge(Object(App\Model\Entity\User), Array, Array)
#7 /var/www/URCA/Toip-Gestion/src/Controller/UsersController.php(87): Cake\ORM\Table->patchEntity(Object(App\Model\Entity\User), Array)
#8 [internal function]: App\Controller\UsersController->edit('35')
#9 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Controller/Controller.php(429): call_user_func_array(Array, Array)
#10 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#11 /var/www/URCA/Toip-Gestion/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#12 /var/www/URCA/Toip-Gestion/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}
```

**Comment by Zehir** [comment]
I looking why I get this error and I think that this commit fix my problem;
https://github.com/cakephp/cakephp/commit/32ee1d72ed8d0170d3491ef9d0d9424817672d6a#diff-b13ca847d0ea573e5909a8284f726a1b

**Comment by lorenzo** [comment]
@Zehir Can you please share the validation code you have in your Table class?

**Comment by Zehir** [comment]
It's was generated by bake plugin
``` php
public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'integer'])
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('login', 'create')
            ->notEmpty('login')
            ->add('login', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->add('last_login', 'valid', ['rule' => 'dateTime'])
            ->allowEmpty('last_login');

        return $validator;
    }
```

**Comment by Zehir** [comment]
I remove my bake template and now I get other rules;
``` php
public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create')
            ->add('id', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->requirePresence('mac', 'create')
            ->notEmpty('mac')
            ->add('mac', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->allowEmpty('ipv4')
            ->add('ipv4', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->allowEmpty('ipv6')
            ->add('ipv6', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->dateTime('last_seen')
            ->allowEmpty('last_seen');

        $validator
            ->allowEmpty('switch');

        $validator
            ->allowEmpty('port');

        $validator
            ->allowEmpty('manufacturer');

        $validator
            ->allowEmpty('model');

        return $validator;
    }
```

**Comment by lorenzo** [comment]
Ok, so it seems like you need to update your bake template

**Comment by Zehir** [comment]
I just updated my bake template and now I dont have any problems.

Thank
