### ISSUE TITLE
[3.2] po file parser throws fatal when dealing with translation comments

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#8337]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: php7 nginx.

### What you did
got translation from .po file with this content:
```
#: firstfile:39
msgid "Pending"
msgstr "En cours"

#: secondfile:12
msgctxt "Pay status"
msgid "Pending"
msgstr "En cours"
```

### Expected Behavior
while the example isnt best case, po file parser should handle it like firstfile having msgctxt - note if i add it to firstfile or remove from secondfile it works 

### Actual Behavior
```
2016-02-24 15:19:46 Warning: Warning (2): Illegal string offset '_context' in [/data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/Parser/PoFileParser.php, line 146]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 147
Cake\I18n\Parser\PoFileParser::_addMessage() - CORE/src/I18n/Parser/PoFileParser.php, line 146
Cake\I18n\Parser\PoFileParser::parse() - CORE/src/I18n/Parser/PoFileParser.php, line 116
Cake\I18n\MessagesFileLoader::__invoke() - CORE/src/I18n/MessagesFileLoader.php, line 139
Cake\I18n\ChainMessagesLoader::__invoke() - CORE/src/I18n/ChainMessagesLoader.php, line 63
Cake\I18n\TranslatorRegistry::Cake\I18n\{closure}() - CORE/src/I18n/TranslatorRegistry.php, line 195
Aura\Intl\PackageLocator::get() - ROOT/vendor/aura/intl/src/Aura/Intl/PackageLocator.php, line 101
Aura\Intl\TranslatorLocator::get() - ROOT/vendor/aura/intl/src/Aura/Intl/TranslatorLocator.php, line 180
Cake\I18n\TranslatorRegistry::_getFromLoader() - CORE/src/I18n/TranslatorRegistry.php, line 237
Cake\I18n\TranslatorRegistry::_getTranslator() - CORE/src/I18n/TranslatorRegistry.php, line 129
Cake\I18n\TranslatorRegistry::get() - CORE/src/I18n/TranslatorRegistry.php, line 104
Cake\I18n\I18n::translator() - CORE/src/I18n/I18n.php, line 144
__ - CORE/src/I18n/functions.php, line 33
require - ROOT/config/bootstrap.php, line 324
[main] - ROOT/webroot/index.php, line 29

2016-02-24 15:19:46 Warning: Warning (2): Illegal string offset '_context' in [/data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/Parser/PoFileParser.php, line 146]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 147
Cake\I18n\Parser\PoFileParser::_addMessage() - CORE/src/I18n/Parser/PoFileParser.php, line 146
Cake\I18n\Parser\PoFileParser::parse() - CORE/src/I18n/Parser/PoFileParser.php, line 116
Cake\I18n\MessagesFileLoader::__invoke() - CORE/src/I18n/MessagesFileLoader.php, line 139
Cake\I18n\ChainMessagesLoader::__invoke() - CORE/src/I18n/ChainMessagesLoader.php, line 63
Cake\I18n\TranslatorRegistry::Cake\I18n\{closure}() - CORE/src/I18n/TranslatorRegistry.php, line 195
Aura\Intl\PackageLocator::get() - ROOT/vendor/aura/intl/src/Aura/Intl/PackageLocator.php, line 101
Aura\Intl\TranslatorLocator::get() - ROOT/vendor/aura/intl/src/Aura/Intl/TranslatorLocator.php, line 180
Cake\I18n\TranslatorRegistry::_getTranslator() - CORE/src/I18n/TranslatorRegistry.php, line 122
Cake\I18n\TranslatorRegistry::get() - CORE/src/I18n/TranslatorRegistry.php, line 104
Aura\Intl\TranslatorLocator::get() - ROOT/vendor/aura/intl/src/Aura/Intl/TranslatorLocator.php, line 188
Cake\I18n\TranslatorRegistry::_getFromLoader() - CORE/src/I18n/TranslatorRegistry.php, line 237
Cake\I18n\TranslatorRegistry::_getTranslator() - CORE/src/I18n/TranslatorRegistry.php, line 129
Cake\I18n\TranslatorRegistry::get() - CORE/src/I18n/TranslatorRegistry.php, line 104
Cake\I18n\I18n::translator() - CORE/src/I18n/I18n.php, line 144
__d - CORE/src/I18n/functions.php, line 81
DebugKit\Panel\TimerPanel::DebugKit\Panel\{closure}() - ROOT/vendor/cakephp/debug_kit/src/Panel/TimerPanel.php, line 54
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 386
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 356
Cake\Controller\Controller::dispatchEvent() - CORE/src/Event/EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE/src/Controller/Controller.php, line 491
Cake\Error\ExceptionRenderer::_getController() - CORE/src/Error/ExceptionRenderer.php, line 126
Cake\Error\ExceptionRenderer::__construct() - CORE/src/Error/ExceptionRenderer.php, line 92
Cake\Error\ErrorHandler::_displayException() - CORE/src/Error/ErrorHandler.php, line 143
Cake\Error\BaseErrorHandler::handleException() - CORE/src/Error/BaseErrorHandler.php, line 180
Cake\Error\BaseErrorHandler::wrapAndHandleException() - CORE/src/Error/BaseErrorHandler.php, line 164
[main] - [internal], line ??

2016-02-24 15:19:46 Error: Fatal Error (1): Uncaught Error: Cannot use string offset as an array in /data/www/beta.cityzenly.com/vendor/cakephp/cakephp/src/I18n/Parser/PoFileParser.php:146
Stack trace:
#0 /data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/Parser/PoFileParser.php(116): Cake\I18n\Parser\PoFileParser->_addMessage(Array, Array)
#1 /data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/MessagesFileLoader.php(139): Cake\I18n\Parser\PoFileParser->parse('/data/www/beta....')
#2 /data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/ChainMessagesLoader.php(63): Cake\I18n\MessagesFileLoader->__invoke()
#3 /data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(195): Cake\I18n\ChainMessagesLoader->__invoke()
#4 /data/www/beta.test.com/vendor/aura/intl/src/Aura/Intl/PackageLocator.php(101): Cake\I18n\TranslatorRegistry->Cake\I18n\{closure}()
#5 /data/www/beta.test.com/vendor/aura/intl/src/Aura/Intl/TranslatorLocator.php(180): Aura\Intl\PackageLocator->get('default', 'fr_FR')
#6 /data/www/ in [/data/www/beta.test.com/vendor/cakephp/cakephp/src/I18n/Parser/PoFileParser.php, line 146]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??
```

**Comment by markstory** [comment]
The issue here is that only some of the matching `msgid` elements have a context. Because of how messages are stored internally if some message values have context, they all need context. While its possible to suppress the notice error, I don't think its possible to retain both the context-less and context-inclusive message without breaking changes.

**Comment by markstory** [comment]
Closing as there is a pull request up to fix the notice error.
