### ISSUE TITLE
3.2.6 Adding a custom view class changes behavior of RequestHandler

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8766]
This is a:
* [x] bug

* CakePHP Version: 3.2.8
* Platform and Target: Apache 7.0.5-3+donate.sury.org~trusty+1

### What you did
* Created bare custom `MobileView.php` in `src/View/`
* Added `$this->viewBuilder()->className('Mobile')` to `AppController::beforeFilter()`

### Expected Behavior
No change.

### Actual Behavior
```bash
2016-05-04 01:07:50 Error: [Cake\View\Exception\MissingTemplateException] Template file "Pages/ajax/about.ctp" is missing.
Exception Attributes: array (
  'file' => 'Pages/ajax/about.ctp',
)
Request URL: /pages/about
Referer URL: https://estatify.dev/
Client IP: 192.168.21.1
Stack Trace:
#0 /var/www/app/vendor/cakephp/cakephp/src/View/View.php(584): Cake\View\View->_getViewFileName('Pages/ajax/abou...')
#1 /var/www/app/vendor/cakephp/cakephp/src/Controller/Controller.php(611): Cake\View\View->render('about', NULL)
#2 /var/www/app/src/Controller/PagesController.php(57): Cake\Controller\Controller->render('about')
#3 [internal function]: App\Controller\PagesController->display('about')
#4 /var/www/app/vendor/cakephp/cakephp/src/Controller/Controller.php(429): call_user_func_array(Array, Array)
#5 /var/www/app/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#6 /var/www/app/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PagesController))
#7 /var/www/app/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#8 {main}
```

It seems that once you use a custom view RequestHandler is being treated differently (possibly correctly) - this should be consistent however in one or the other way.

### Bare MobileView.php
```php
<?php
namespace App\View;

use Cake\View\View;

/**
 * Mobile View
 *
 * For Android and iOS Mobile Devices
 *
 */
class MobileView extends View
{
}
```
### AppController.php
```php
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link http://book.cakephp.org/3.0/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{

    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('Security');`
     *
     * @return void
     */
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
    }

    public function beforeFilter(Event $event) {
        parent::beforeFilter($event);
        // $this->viewBuilder()->className('Mobile'); // Uncomment => different behavior?
        $this->viewBuilder()->layout('default.mobile');
        if ($this->request->is('ajax') === true) {
            $this->viewBuilder()->layout('xhr');
        }
    }

    /**
     * Before render callback.
     *
     * @param \Cake\Event\Event $event The beforeRender event.
     * @return void
     */
    public function beforeRender(Event $event)
    {
        if (!array_key_exists('_serialize', $this->viewVars) &&
            in_array($this->response->type(), ['application/json', 'application/xml'])
        ) {
            $this->set('_serialize', true);
        }
    }
}
```

**Comment by markstory** [comment]
The different behavior is intentional. When a controller explicitly sets a view class to be used, RequestHandler will not overwrite that view class setting. This was done in #7479 to fix #7452 (an earlier regression).

**Comment by ionas** [comment]
Looking at https://github.com/cakephp/cakephp/pull/7479/files it looks like `RequestHandler` is setting `Cake\View\View`.

What I don't understand is that if I create a bare class that extends `Cake\View\View`, that in conclusion templates are looked up in different path's e.g. in Pages/**ajax**/about.ctp

> RequestHandler will not overwrite that view class setting.
https://github.com/cakephp/cakephp/pull/7479/files#diff-025d59b0b75625e9fd100cc44fae82f7R552
I don't understand where RequstHandler passes along settings here? What's the difference between that and my custom view class setup that *does nothing* different than the class setup by RequestHandler anyway?!

**Comment by hmic** [comment]
WIthout the details, I do understand that RequestHandler does handle a custom View class differently. I think this is a good thing to do and neccessary too: I do have custom Excel and Pdf View classes that I do not want RequestHandler to interfere with, they do not render html or even output directly...

It's still kind of unexpected and a quite a bit of (black) magic at work. Maybe it just needs better documentation or another method to force/disable the magic...

**Comment by ionas** [comment]
If I disable RequestHandler entirely, my custom class works again and detects /pages/about.ctp`
E.g. if setting a custom View class RequestHandler is still messing with it in some wired way?!

e.g. this works
```php
    public function initialize()
    {
        parent::initialize();
        // $this->loadComponent('RequestHandler');
    }

    public function beforeFilter(Event $event) {
        parent::beforeFilter($event);
        $this->viewBuilder()->className('Mobile');
        $this->viewBuilder()->layout('default.mobile');
        if ($this->request->is('ajax') === true) {
            $this->viewBuilder()->layout('xhr');
        }
    }
```
However I want to use `RequestHandler` for mobile user agent detection.

**Comment by ADmad** [comment]
Use beforeRender() instead of beforeFilter().
