### ISSUE TITLE
Serialisation error 

### ISSUE THREAD

**Issue by ross-chater** [cakephp/cakephp#9622]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.12
* Platform and Target: Apache 2, PHP 7

### What you did
When using a JSON extension, normal exceptions throw 500 errors instead with debug mode = true

"message": "[RuntimeException] Serialization of View data failed.\n#0 /pathtomyproject/vendor/cakephp/cakephp/src/View/JsonView.php(107): Cake\\View\\SerializedView->render('error500', 'error')\n#1

### What happened
After digging into the JsonView.php function _serialize() json_encode is generating a recursion error using json_last_error(), if I remove the "trace" item from the return of _dataToSerialize, everything works fine.. The traces are usually pretty large so trying to drill down to find the exact cause is just a nightmare....

Any ideas? 

### Expected Behavior
An exception should be thrown with the correct text, instead a 500 with the above is shown..

**Comment by thinkingmedia** [comment]
Is cake using JsonView to render the error message?

**Comment by ross-chater** [comment]
Yes that's correct

**Comment by thinkingmedia** [comment]
Do you have a local `ErrorController` object in your project, or are you using the one from the core.

The App template now comes with its own `ErrorController` class.

https://github.com/cakephp/app/blob/master/src/Controller/ErrorController.php

If you want to continue and use Json for error responses. You can add this code.

```
    /**
     * beforeRender callback.
     *
     * @param \Cake\Event\Event $event Event.
     * @return void
     */
    public function beforeRender(Event $event)
    {
        if ($this->RequestHandler->ext === 'json') {
            $this->viewBuilder()->className('Json');
        }
        $this->viewBuilder()->templatePath('Error');
    }
```

**Comment by ross-chater** [comment]
public function __construct($request = null, $response = null) {
        parent::__construct($request, $response);
        $this->viewBuilder()->className('Json');
        $this->viewBuilder()->templatePath('Error');
    }

I'm forcing all errors to display in JSON format as its a JSON based API, that's the sole use of this application.

**Comment by thinkingmedia** [comment]
Does your `ErrorController` extend `AppController`?

The recursion error you are reporting is often the result of an error being thrown while trying to render the error view. This triggers a recursion on reporting an error for itself.

**Comment by ross-chater** [comment]
ErrorController.php

```
<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Routing\Router;
use Cake\Event\Event;

class ErrorController extends AppController {

    public function __construct($request = null, $response = null) {
        parent::__construct($request, $response);
        $this->viewBuilder()->className('Json');
        $this->viewBuilder()->templatePath('Error');
    }

}
```

For more info on exactly where the issue is on the debug section, this should be showing a function not found error as I purposefully miss typed $this->**WrongModelNames**->find() 

```
"trace": [
      {
        "file": "/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php",
        "line": 126,
        "function": "handleFatalError",
        "class": "Cake\\Error\\BaseErrorHandler",
        "type": "->",
        "args": [
          256,
          "[RuntimeException] Serialization of View data failed.\n#0 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/View/JsonView.php(107): Cake\\View\\SerializedView->render('error500', 'error')\n#1 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(356): Cake\\View\\JsonView->render('error500', 'error')\n#2 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(335): Cake\\Error\\ExceptionRenderer->_outputMessageSafe('error500')\n#3 /var/www/pathtomyproject/vendor/friendsofcake/crud/src/Error/ExceptionRenderer.php(76): Cake\\Error\\ExceptionRenderer->_outputMessage('error')\n#4 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(192): Crud\\Error\\ExceptionRenderer->_outputMessage('error')\n#5 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(144): Cake\\Error\\ExceptionRenderer->render()\n#6 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(179): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\PHP7ErrorException))\n#7 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(163): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\PHP7ErrorException))\n#8 [internal function]: Cake\\Error\\BaseErrorHandler->wrapAndHandleException(Object(Cake\\Error\\PHP7ErrorException))\n#9 {main}",
          "/var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ErrorHandler.php",
          156
        ]
      },
      {
```

**Comment by markstory** [comment]
You should try upgrading CakePHP. There were a few bugfixes related to JSON serialization after 3.1.12.

**Comment by ross-chater** [comment]
I'll give that shot!

**Comment by ross-chater** [comment]
3.3.6 still returning same errors on serialisation. I put the trace into this function which detects recursion on all levels

```
      function is_recursive(array &$array, array &$alreadySeen = array()) {
            static $uniqueObject;
            if (!$uniqueObject) {
                $uniqueObject = new \stdClass;
            }

            $alreadySeen[] = &$array;

            foreach ($array as &$item) {
                if (!is_array($item)) {
                    continue;
                }

                $item[] = $uniqueObject;
                $recursionDetected = false;
                foreach ($alreadySeen as $candidate) {
                    if (end($candidate) === $uniqueObject) {
                        $recursionDetected = true;
                        break;
                    }
                }

                array_pop($item);

                if ($recursionDetected || is_recursive($item, $alreadySeen)) {
                    return true;
                }
            }

            return false;
        }
        die(debug(is_recursive($this->_dataToSerialize($serialize)));
```
The above die debug returns false, so for some reason even though its not recursive json_encode still thinks its recursive....

Its blowing my mind.

**Comment by ross-chater** [comment]
I've found what is causing the issue... But I have no idea why
```

`                                    [RequestHandler] => Cake\Controller\Component\RequestHandlerComponent Object
                                        (
                                            [components] => Array
                                                (
                                                )

                                            [implementedEvents] => Array
                                                (
                                                    [Controller.startup] => startup
                                                    [Controller.beforeRender] => beforeRender
                                                    [Controller.beforeRedirect] => beforeRedirect
                                                )

                                            [_config] => Array
                                                (
                                                    [checkHttpCache] => 1
                                                    [viewClassMap] => Array
                                                        (
                                                            [json] => Json
                                                            [xml] => Xml
                                                            [ajax] => Ajax
                                                        )

                                                    [inputTypeMap] => Array
                                                        (
                                                            [json] => Array
                                                                (
                                                                    [0] => json_decode
                                                                    [1] => 1
                                                                )

                                                            [xml] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [0] => Cake\Controller\Component\RequestHandlerComponent Object
 *RECURSION*
                                                                            [1] => convertXml
                                                                        )

                                                                )

                                                        )

                                                    [enableBeforeRedirect] => 1
                                                )

                                        )`
```

**Comment by ross-chater** [comment]
And even further...  

```
App\Controller\Client\V1\DivisionsController Object
(
    [interfaceVersion] => v1
    [apiVersion] => 1.0.2
    [name] => Divisions
    [helpers] => Array
        (
        )
    [_components:protected] => Cake\Controller\ComponentRegistry Object
        (
            [_Controller] => App\Controller\Client\V1\DivisionsController Object
 *RECURSION*
```

**Comment by ross-chater** [comment]
This bug is introduced when using Crud components Crud.Api listener...

Will close this issue now.

Thanks everyone who helped.

**Comment by yomexzo** [comment]
Looks like this could still be an issue.

I was wondering why `trace` was not coming up in JSON responses when an exception is thrown so I started digging. Ended up realizing it wasn't added to the `_serialize` `viewVars` at https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L194.

After I added it, the app started choking while trying to render. After further digging, I realized it happened within the `_serialize` function of `JsonView` while trying to `json_encode`. Below is a sample dump of an array `json_encode` chokes on.

NB: `json_encode` works fine without the `args` (I manually unset it). 

This might be a PHP issue but not sure how much it relates with Cake since it is choking because of the Query object in the `args`

```
/src/Error/ExceptionRenderer.php (line 193)
[
    'file' => '/root-path/vendor/cakephp/cakephp/src/Database/Query.php',
    'line' => (int) 219,
    'function' => 'run',
    'class' => 'Cake\Database\Connection',
    'type' => '->',
    'args' => [
        (int) 0 => object(App\Model\Query) {

            '(help)' => 'This is a Query object, to get the results execute or iterate it.',
            'sql' => 'SELECT 1 AS `existing` FROM organizations Organization WHERE Organizations.id = :c0 LIMIT 1',
            'params' => [
                ':c0' => [
                    'value' => (int) 1,
                    'type' => null,
                    'placeholder' => 'c0'
                ]
            ],
            'defaultTypes' => [
                'Organization__id' => 'integer',
                'Organization.id' => 'integer',
                'id' => 'integer',
                'Organization__product_count' => 'integer',
                'Organization.product_count' => 'integer',
                'product_count' => 'integer',
                'Organization__created_by' => 'integer',
                'Organization.created_by' => 'integer',
                'created_by' => 'integer',
                'Organization__admin_created' => 'integer',
                'Organization.admin_created' => 'integer',
                'admin_created' => 'integer',
                'Organization__name' => 'string',
                'Organization.name' => 'string',
                'name' => 'string',
                'Organization__website' => 'string',
                'Organization.website' => 'string',
                'website' => 'string',
                'Organization__logo' => 'string',
                'Organization.logo' => 'string',
                'logo' => 'string',
                'Organization__address' => 'text',
                'Organization.address' => 'text',
                'address' => 'text',
                'Organization__landmark' => 'string',
                'Organization.landmark' => 'string',
                'landmark' => 'string',
                'Organization__city' => 'string',
                'Organization.city' => 'string',
                'city' => 'string',
                'Organization__state_id' => 'integer',
                'Organization.state_id' => 'integer',
                'state_id' => 'integer',
                'Organization__country' => 'string',
                'Organization.country' => 'string',
                'country' => 'string',
                'Organization__created' => 'datetime',
                'Organization.created' => 'datetime',
                'created' => 'datetime',
                'Organization__modified' => 'datetime',
                'Organization.modified' => 'datetime',
                'modified' => 'datetime',
                'Organization__request_id' => 'integer',
                'Organization.request_id' => 'integer',
                'request_id' => 'integer'
            ],
            'decorators' => (int) 0,
            'executed' => false,
            'hydrate' => false,
            'buffered' => true,
            'formatters' => (int) 1,
            'mapReducers' => (int) 0,
            'contain' => [],
            'matching' => [],
            'extraOptions' => [],
            'repository' => object(App\Model\Table\OrganizationsTable) {

                'registryAlias' => 'Organization',
                'table' => 'organizations',
                'alias' => 'Organization',
                'entityClass' => 'App\Model\Entity\Organization',
                'associations' => [
                    (int) 2 => 'products',
                    (int) 3 => 'orders',
                ],
                'behaviors' => [
                    (int) 0 => 'Timestamp'
                ],
                'defaultConnection' => 'default',
                'connectionName' => 'default'
            
            }
        
        }
    ]
]```

**Comment by yomexzo** [comment]
Actually, it might be a false alarm. Although a problem still exists.

I just went through `jsonSerialize()` in `Query.php`. It is trying to `$this->all();` which would lead to the same error that led to the exception being rendered in the first place.
