### ISSUE TITLE
"HTTP/1.1 400" is not valid header name

### ISSUE THREAD

**Issue by binarycrafts** [cakephp/cakephp#9778]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8
* Platform and Target: nginx, postgres, phpleague/oauth2-server v.4, uafrica/oauth-server

### What you did
GET request to a Cake controller which is declined by the OAuth server w/ 400 HTTP code.

### What happened
The header returned by phpleague/oauth2-server HTTP/1.1 400 is invalidated by Zend\Diactoros
I see
"HTTP/1.1 400" is not valid header name

### What you expected to happen
The header should not be invalidated and the regular 400 response should be returned.

**Comment by markstory** [comment]
What is the stacktrace on that error?

**Comment by binarycrafts** [comment]
```
"Stack Trace:"
"#0 /var/www/vendor/zendframework/zend-diactoros/src/Response.php(193): Zend\Diactoros\HeaderSecurity::assertValidName('HTTP/1.1 400')"
"#1 /var/www/vendor/zendframework/zend-diactoros/src/Response.php(126): Zend\Diactoros\Response->assertHeaders(Array)"
"#2 /var/www/vendor/cakephp/cakephp/src/Http/ResponseTransformer.php(171): Zend\Diactoros\Response->__construct(Object(Zend\Diactoros\Stream), 400, Array)"
"#3 /var/www/vendor/cakephp/cakephp/src/Http/BaseApplication.php(86): Cake\Http\ResponseTransformer::toPsr(Object(Cake\Network\Response))"
"#4 /var/www/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))"
"#5 /var/www/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))"
"#6 /var/www/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))"
"#7 /var/www/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))"
"#8 /var/www/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))"
"#9 /var/www/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))"
"#10 /var/www/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))"
"#11 /var/www/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))"
"#12 /var/www/vendor/cakephp/cakephp/src/Http/Server.php(92): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))"
"#13 /var/www/webroot/index.php(37): Cake\Http\Server->run()"
"#14 {main}"

**Comment by markstory** [comment]
Ok, what is setting the invalid header value? It doesn't look like any of the core CakePHP components are involved from that trace.

**Comment by markstory** [comment]
Ping.

**Comment by binarycrafts** [comment]
The header is set by phpleague/oauth2-server.
It s possible that my version of the server is not setting a PSR-7 compatible header.
Do I need to disable the Cake middleware entirely or is there a way to work around this?

**Comment by markstory** [comment]
Is phpleague/oauth2-server a PSR7 middleware/component? If so it shouldn't be setting the status code via a header.

**Comment by binarycrafts** [comment]
PSR7 support is a work in progress and my guess is that it s not there yet or my version is outdated.
Thanks,m Ill just close this.

**Comment by akoSalman** [comment]
I changed `GET` method to `POST` and worked fine.
