### ISSUE TITLE
Add support for exception chaining

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9824]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.9 / 2.9.3

### What you did

Chained exceptions:
```php
try {
    throw new \Exception('Foo');
} catch (\Exception $e) {
    throw new \Exception('Bar', 0, $e);
}
```

### What happened

The chained exceptions were not rendered/logged:
```
2016-12-01 18:27:49 Error: [Exception] Bar
Request URL: /somethings/
Client IP: 127.0.0.1
Stack Trace:
#0 [internal function]: App\Controller\SomethingsController->index()
#1 C:\var\www\cakephp3.dev\vendor\cakephp\cakephp\src\Controller\Controller.php(435): call_user_func_array(Array, Array)
#2 C:\var\www\cakephp3.dev\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(122): Cake\Controller\Controller->invokeAction()
#3 C:\var\www\cakephp3.dev\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(96): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\SomethingsController))
#4 C:\var\www\cakephp3.dev\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(60): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\var\www\cakephp3.dev\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}
```

### What you expected to happen

The chained exceptions are rendered/logged, like the PHP built-in exception handler:
```
Fatal error: Uncaught exception 'Exception' with message 'Foo' in C:\var\sandbox\test.php:3
Stack trace:
#0 {main}

Next exception 'Exception' with message 'Bar' in C:\var\sandbox\test.php:5
Stack trace:
#0 {main}
  thrown in C:\var\sandbox\test.php on line 5
```

I would like to add the new third argument `$previous` to all existing core exception classes, and to fix `ErrorHandler` and several core view templates (such as `exception_stack_trace.ctp`) to render chained exceptions correctly.

Now I am targeting 3.4.0 and 2.10.0 (Next minor versions).

**Comment by dereuromark** [comment]
:+1: Yes, please do.

**Comment by markstory** [comment]
Sounds like a great idea! Any thoughts on how we could render nested exceptions in the error pages?

**Comment by chinpei215** [comment]
The implementation would be like this:
```php
<?php
for ($e = $error; $e; $e = $e->getPrevious()) {
    if (in_array($e, $errors, true)) {
        break; // I think we should break if chained exceptions contained
    }
    $errors[] = $e;
}
// $errors = array_reverse($errors); 
```
Display order might be arguable. Also, adding `getChainedExceptions()`, that contained the above code,  into our base `Exception` class would be better, as we would use the method at least when rendering and logging.

Regarding to the appearance, I have two ideas now:
## 1. Chain
![chained-exceptions1](https://cloud.githubusercontent.com/assets/7399393/20828197/9b0e5240-b8b9-11e6-9ce1-4b7718333e81.png)

## 2. Paginate
![chained-exceptions2](https://cloud.githubusercontent.com/assets/7399393/20828685/0e57ba3c-b8bc-11e6-9a43-952ae94b3fe2.png)

**Comment by dereuromark** [comment]
I would like to see them in reverse order (newest one on top), which is what I think intuitively people will expect. But the ordering should maybe be more clear - the 1./2. doesnt say this.
Maybe we don't need the numbering, and instead describe it?
```
H1 BarException
...

H2 Previous exceptions

H3 FooException
...

H3 InitialException
....
```
etc?

**Comment by chinpei215** [comment]
Sounds reasonable to me. I prefer describing over numbering.
Also, I forgot to show messages of chained exceptions in the first idea. It would be important to show them.

> How does whoops etc handle it?

What do you mean?

**Comment by dereuromark** [comment]
Ah, they are numbering it in the order they occur, but highlight the last one by default:
http://filp.github.io/whoops/demo/
That seems also quite clear to me. So I would be fine with that, too.

**Comment by chinpei215** [comment]
I didn't think "woops" is a proper noun 😛  I'll check it out.

**Comment by chinpei215** [comment]
Woops seems to merge stack traces in a graceful way. Now I am guessing that @markstory would have mentioned it  above. My above code is totally bad 😛 My code would duplicate stack traces if exceptions are thrown in the same stack.

**Comment by markstory** [comment]
@chinpei215 The unpaginated stack trace looks great!

**Comment by chinpei215** [comment]
OK. I'll learn whoops and implement a nice unpaginated stack trace as much as possible I can.

**Comment by chinpei215** [comment]
Sorry, I become busy for a while. This enhancement may not make it in time for 3.4 :bow:

**Comment by markstory** [comment]
Not a problem @chinpei215 :+1:

**Comment by Oxicode** [comment]
+1

**Comment by dereuromark** [comment]
We should include/promote whoops, I have been using it for a while now for the [sandbox](sandbox.dereuromark.de), and it really works nicely.

**Comment by Oxicode** [comment]
> We should include/promote whoops, I have been using it for a while now for the sandbox, and it really works nicely.


Link broke

**Comment by dereuromark** [comment]
Fixed, it is just a project where you can test it locally already.
But adding your own handler as outlined in the [whoops plugin](https://github.com/gourmet/whoops) also is quite straightforward.

**Comment by dereuromark** [comment]
PS: Did someone get editor opening to work? See https://github.com/gourmet/whoops/pull/13

**Comment by chinpei215** [comment]
@dereuromark I haven't done anything yet. Can we move the code into core?

**Comment by chinpei215** [comment]
I decided to **not** try to merge stack frames in our error page. While I read the source cod of Whoops, I realized Whoops merges them incorrectly sometimes. The following code is an example that causes the problem:
```php
function test($message, $previous = null) {
    throw new Exception($message, 0, $previous);
}

for ($n = 1, $e = null;; ++$n) {
    try {
        test($n, $e);
    } catch (Exception $e) {
        if ($n >= 3) {
            throw $e;
        }
    }
}
```
In the above case, the stack frames should be as follows:
```
Fatal error: Uncaught exception 'Exception' with message '1' in /path/to/foo.php:3
Stack trace:
#0 /path/to/foo.php(8): test(1, NULL)
#1 {main}

Next exception 'Exception' with message '2' in /path/to/foo.php:3
Stack trace:
#0 /path/to/foo.php(8): test(2, Object(Exception))
#1 {main}

Next exception 'Exception' with message '3' in /path/to/foo.php:3
Stack trace:
#0 /path/to/foo.php(8): test(3, Object(Exception))
#1 {main}
  thrown in /path/to/foo.php on line 3
```
However Whoops shows the most outer exception only, as chained exceptions are thrown at the same line in the same. In such cases, Whoops removes them incorrectly in their merge algorithm.

**Comment by chinpei215** [comment]
The following is an example of a logged exception in the current version:
```
2017-10-08 09:24:14 Error: [Cake\Network\Exception\InternalErrorException] Internal Server Error
Request URL: /example/
Referer URL: https://cakephp.org/
Stack Trace:
#0 /path/to/CORE/src/Controller/Controller.php(435): App\Controller\ExamplesController->index()
#1 /path/to/CORE/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#2 /path/to/CORE/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ExamplesController))
#3 /path/to/CORE/src/Http/BaseApplication.php(103): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /path/to/CORE/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 /path/to/CORE/src/Routing/Middleware/RoutingMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /path/to/CORE/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /path/to/CORE/src/Error/Middleware/ErrorHandlerMiddleware.php(95): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /path/to/CORE/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /path/to/CORE/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /path/to/CORE/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /path/to/APP/webroot/index.php(41): Cake\Http\Server->run()
#14 {main}
```

The following is what I am thinking now for logging chained exceptions:
```
2017-10-08 09:24:14 Error: [Cake\Network\Exception\InternalErrorException] Internal Server Error
Request URL: /example/
Referer URL: https://cakephp.org/

Exception 'Cake\Network\Exception\InternalErrorException' with message 'Internal Server Error' in /path/to/ExamplesController.php:18
Stack Trace:
#0 /path/to/CORE/src/Controller/Controller.php(435): App\Controller\ExamplesController->index()
#1 /path/to/CORE/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#2 /path/to/CORE/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ExamplesController))
#3 /path/to/CORE/src/Http/BaseApplication.php(103): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /path/to/CORE/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 /path/to/CORE/src/Routing/Middleware/RoutingMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /path/to/CORE/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /path/to/CORE/src/Error/Middleware/ErrorHandlerMiddleware.php(95): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /path/to/CORE/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /path/to/CORE/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /path/to/CORE/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /path/to/APP/webroot/index.php(41): Cake\Http\Server->run()
#14 {main}

Previous exception 'LogicException' with 'Never come here' in /path/to/ExamplesController.php:16
#0 /path/to/CORE/src/Controller/Controller.php(435): App\Controller\ExamplesController->index()
#1 /path/to/CORE/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#2 /path/to/CORE/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ExamplesController))
#3 /path/to/CORE/src/Http/BaseApplication.php(103): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /path/to/CORE/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 /path/to/CORE/src/Routing/Middleware/RoutingMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /path/to/CORE/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /path/to/CORE/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /path/to/CORE/src/Error/Middleware/ErrorHandlerMiddleware.php(95): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /path/to/CORE/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /path/to/CORE/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /path/to/CORE/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /path/to/APP/webroot/index.php(41): Cake\Http\Server->run()
#14 {main}
```

If you have other ideas, please tell me. I am planning to implement this feature on the next weekend.

**Comment by markstory** [comment]
I think the proposed log format looks good. It is clear what is going on and that chained exceptions are being handled.

**Comment by chinpei215** [comment]
Thank you.

**Comment by ADmad** [comment]
@chinpei215 Would be great to have this in 4.0 :slightly_smiling_face:.

**Comment by chinpei215** [comment]
@ADmad Sorry, I overlooked at your message. It is hard to say but unfortunately I lost my commits (the .git directory) accidentally 😞.

**Comment by dereuromark** [comment]
This is tagged to "future", is this still intended to go into 4.x?
